[version]
current = "2.5.0"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "chore: bumped version to {new_version}"
tag_template = "{new_version}"

[[file]]
src = "pyproject.toml"
search = 'version = "{current_version}"'

[[file]]
src = "src/flockwave/spec/version.py"
version_template = "({major}, {minor}, {patch})"
search = "__version_info__ = {current_version}"

[[before_commit]]
name = "Run tests"
cmd = "uv sync && uv run pytest && pre-commit run --all-files"

[[before_commit]]
name = "Build the TypeScript definitions"
cmd = "npm run build"

# [[file]]
# src = "package.json"
# search = '"version" = "{current_version}"'

[[before_commit]]
name = "Update package.json and package-lock.json"
cmd = "npm version --no-git-tag-version {new_version}"
