/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HttpCollmotComSchemasFlockwave10MessageJson = StandardMessage | ErrorMessage;
/**
 * Identifier of the message
 */
export type MessageID = string;
export type HttpCollmotComSchemasFlockwave10MessageBodyJson =
  | null
  | HttpCollmotComSchemasFlockwave10NotificationBodyJson
  | HttpCollmotComSchemasFlockwave10RequestBodyJson
  | HttpCollmotComSchemasFlockwave10ResponseBodyJson;
export type HttpCollmotComSchemasFlockwave10NotificationBodyJson =
  | Notification_ASYNCRESP
  | Notification_ASYNCST
  | Notification_ASYNCTIMEOUT
  | Notification_CONNDEL
  | Notification_OBJDEL
  | Notification_SYSCLOSE
  | Notification_SYSMSG;
/**
 * Identifier of the receipt
 */
export type ReceiptID = string;
/**
 * Identifier of a single connection
 */
export type ConnectionID = string;
/**
 * Identifier of a single object
 */
export type ObjectID = string;
/**
 * Severity of the message
 */
export type Severity = "debug" | "info" | "warning" | "error" | "critical";
export type HttpCollmotComSchemasFlockwave10RequestBodyJson =
  | Request_ASYNCCANCEL
  | Request_ASYNCRESUME
  | Request_AUTHINF
  | Request_AUTHREQ
  | Request_AUTHWHOAMI
  | Request_BCNINF
  | Request_BCNPROPS
  | Request_CLKINF
  | Request_CLKLIST
  | Request_CONNINF
  | Request_CONNLIST
  | Request_DEVINF
  | Request_DEVLIST
  | Request_DEVLISTSUB
  | Request_DEVSUB
  | Request_DEVUNSUB
  | Request_DOCKINF
  | Request_EXTCFG
  | Request_EXTINF
  | Request_EXTLIST
  | Request_EXTLOAD
  | Request_EXTRELOAD
  | Request_EXTSETCFG
  | Request_EXTUNLOAD
  | Request_FWOBJECTLIST
  | Request_FWTARGETINF
  | Request_FWTARGETLIST
  | Request_FWUPLOAD
  | Request_LCNINF
  | Request_LOGDATA
  | Request_LOGINF
  | Request_OBJCMD
  | Request_OBJLIST
  | Request_PRMGET
  | Request_PRMSET
  | Request_PRMSETMANY
  | Request_RTKINF
  | Request_RTKLIST
  | Request_RTKSOURCE
  | Request_RTKSTAT
  | Request_RTKSURVEY
  | Request_SHOWCFG
  | Request_SHOWSETCFG
  | Request_SHOWLIGHTS
  | Request_SHOWSETLIGHTS
  | Request_SYSPING
  | Request_SYSPORTS
  | Request_SYSTIME
  | Request_SYSVER
  | Request_UAVCALIB
  | Request_UAVFLY
  | Request_UAVHALT
  | Request_UAVHOVER
  | Request_UAVINF
  | Request_UAVLAND
  | Request_UAVLIST
  | Request_UAVMOTOR
  | Request_UAVPREFLT
  | Request_UAVRST
  | Request_UAVRTH
  | Request_UAVSIGNAL
  | Request_UAVSLEEP
  | Request_UAVTAKEOFF
  | Request_UAVTEST
  | Request_UAVVER
  | Request_UAVWAKEUP
  | Request_WTHAT
  | Request_WTHINF
  | Request_WTHLIST;
/**
 * Session ID for multi-step authentication methods
 */
export type SessionID = number;
/**
 * Identifier of a single clock
 */
export type ClockID = string;
/**
 * Identifier of a single extension
 */
export type ExtensionID = string;
/**
 * Identifier of a single firmware update target
 */
export type FirmwareUpdateTargetID = string;
/**
 * Identifier of a single flight log
 */
export type FlightLogID = string;
/**
 * Positional arguments of the command
 */
export type Arguments = unknown[];
/**
 * Identifier of an RTK preset
 */
export type RTKPresetID = string;
/**
 * RTK message set to use
 */
export type MessageSet = "msm4" | "msm7";
/**
 * Earth-centered Earth-fixed coordinate of an object
 *
 * @minItems 3
 */
export type ECEFCoordinate = [number, number, number];
/**
 * Scope of the show authorization
 */
export type AuthorizationScope = "none" | "live" | "rehearsal" | "lights";
/**
 * GPS coordinate of an object
 *
 * @minItems 2
 */
export type GPSCoordinate =
  | [Latitude, Longitude]
  | [Latitude, Longitude, AMSL]
  | [Latitude, Longitude, AMSL, AHL]
  | [Latitude, Longitude, AMSL, AHL, AGL];
/**
 * Latitude, in 1e-7 degrees
 */
export type Latitude = number;
/**
 * Longitude, in 1e-7 degrees
 */
export type Longitude = number;
/**
 * Altitude above mean sea level, in millimeters
 */
export type AMSL = number | null;
/**
 * Altitude above home level, in millimeters
 */
export type AHL = number | null;
/**
 * Altitude above ground level, in millimeters
 */
export type AGL = number | null;
export type HttpCollmotComSchemasFlockwave10ResponseBodyJson =
  | Response_ACKACK
  | Response_ACKNAK
  | Response_ASYNCCANCEL
  | Response_ASYNCRESUME
  | Response_AUTHINF
  | (Response_AUTHRESP_SingleStep | Response_AUTHRESP_MultiStep)
  | Response_AUTHWHOAMI
  | Response_BCNINF
  | Response_BCNPROPS
  | Response_CLKINF
  | Response_CLKLIST
  | Response_CONNINF
  | Response_CONNLIST
  | Response_DEVINF
  | Response_DEVLIST
  | Response_DEVLISTSUB
  | Response_DEVSUB
  | Response_DEVUNSUB
  | Response_DOCKINF
  | Response_EXTCFG
  | Response_EXTINF
  | Response_EXTLIST
  | Response_EXTLOAD
  | Response_EXTRELOAD
  | Response_EXTSETCFG
  | Response_EXTUNLOAD
  | Response_FWOBJECTLIST
  | Response_FWTARGETINF
  | Response_FWTARGETLIST
  | Response_FWUPLOAD
  | Response_LCNINF
  | Response_LOGDATA
  | Response_LOGINF
  | Response_OBJCMD
  | Response_OBJLIST
  | Response_PRMGET
  | Response_PRMSET
  | Response_PRMSETMANY
  | Response_RTKINF
  | Response_RTKLIST
  | Response_RTKSOURCE
  | Response_RTKSTAT
  | Response_RTKSURVEY
  | Response_SHOWCFG
  | Response_SHOWLIGHTS
  | Response_SYSPORTS
  | Response_SYSTIME
  | Response_SYSVER
  | Response_UAVCALIB
  | Response_UAVFLY
  | Response_UAVHALT
  | Response_UAVHOVER
  | Response_UAVINF
  | Response_UAVLAND
  | Response_UAVLIST
  | Response_UAVMOTOR
  | Response_UAVPREFLT
  | Response_UAVRST
  | Response_UAVRTH
  | Response_UAVSIGNAL
  | Response_UAVSLEEP
  | Response_UAVTAKEOFF
  | Response_UAVTEST
  | Response_UAVVER
  | Response_UAVWAKEUP
  | Response_WTHAT
  | Response_WTHINF
  | Response_WTHLIST;
/**
 * Purpose of the connection
 */
export type Purpose = "debug" | "dock" | "dgps" | "gps" | "time" | "uavRadioLink" | "mocap" | "other";
/**
 * Status of the connection
 */
export type ConnectionStatus = "disconnected" | "connecting" | "connected" | "disconnecting" | "unknown";
/**
 * Type of a device tree node
 */
export type DeviceTreeNodeType = "root" | "object" | "device" | "channel";
/**
 * Type of a channel
 */
export type ChannelType =
  | "audio"
  | "boolean"
  | "bytes"
  | "cartesian"
  | "color"
  | "duration"
  | "gps"
  | "number"
  | "object"
  | "string"
  | "time"
  | "video";
/**
 * Class of a device
 */
export type DeviceClass =
  | "accelerometer"
  | "actuator"
  | "altimeter"
  | "battery"
  | "camera"
  | "cpu"
  | "cpuCore"
  | "gps"
  | "group"
  | "gyroscope"
  | "led"
  | "magnetometer"
  | "microphone"
  | "misc"
  | "pyro"
  | "radio"
  | "rangefinder"
  | "rc"
  | "rotor"
  | "sensor"
  | "speaker"
  | "sprayer";
/**
 * Operation that can be performed on a channel
 */
export type ChannelOperation = "read" | "write";
export type LicenseID = string;
/**
 * Identifier of a flight log kind
 */
export type FlightLogKind = "text" | "ardupilot" | "ulog" | "flockctrl" | "unknown";
/**
 * The type of the preset (built-in, created automatically or added by the user)
 */
export type RTKPresetType = "builtin" | "dynamic" | "user";
/**
 * Format of the GPS messages arriving in this configuration
 */
export type MessageFormat = "auto" | "rtcm2" | "rtcm3" | "ubx";
export type StationID = number;
/**
 * RTK message observation statistics
 *
 * @minItems 2
 */
export type RTKMessageObservations = [number, number];
/**
 * Position in a local right-handed XYZ coordinate system
 *
 * @minItems 3
 */
export type PositionXYZ = [number, number, number];
/**
 * Basic information about the GPS fix
 *
 * @minItems 1
 */
export type GPSFix =
  | [number]
  | [number, number | null]
  | [number, number | null, number | null]
  | [number, number | null, number | null, number | null];
/**
 * Attitude around the principal aircraft axes
 *
 * @minItems 3
 */
export type Attitude = [RollAngle, PitchAngle, YawAngle];
/**
 * Roll angle, in 1/10th of degrees
 */
export type RollAngle = number;
/**
 * Pitch angle, in 1/10th of degrees
 */
export type PitchAngle = number;
/**
 * Yaw angle, in 1/10th of degrees
 */
export type YawAngle = number;
/**
 * Velocity in the NED coordinate system
 *
 * @minItems 3
 */
export type VelocityNED = [number, number, number];
/**
 * Velocity in a local right-handed XYZ coordinate system
 *
 * @minItems 3
 */
export type VelocityXYZ = [number, number, number];
/**
 * Information about the on-board battery of the UAV, if applicable
 *
 * @minItems 1
 */
export type BatteryInformation = [number] | [number, number] | [number, number, boolean];
/**
 * Result of the preflight check or a single item in a preflight checklist
 */
export type PreflightCheckResult = "off" | "pass" | "warning" | "running" | "softFailure" | "failure" | "error";
/**
 * Magnetic vector
 */
export type MagneticVector = [] | [number] | [number, number] | [number, number, number];

export interface StandardMessage {
  /**
   * Version number in major.minor.patch format; minor and patch versions are optional
   */
  "$fw.version": string;
  id: MessageID;
  refs?: MessageID;
  body: HttpCollmotComSchemasFlockwave10MessageBodyJson;
  [k: string]: unknown;
}
export interface Notification_ASYNCRESP {
  type: "ASYNC-RESP";
  id: ReceiptID;
  error?: string;
  result?: unknown;
  [k: string]: unknown;
}
export interface Notification_ASYNCST {
  type: "ASYNC-ST";
  id: ReceiptID;
  progress: ProgressInformation;
  suspended?: boolean;
  [k: string]: unknown;
}
/**
 * Progress of some operation being executed on a UAV
 */
export interface ProgressInformation {
  percentage?: number;
  message?: string;
  object?: {
    [k: string]: unknown;
  };
}
export interface Notification_ASYNCTIMEOUT {
  type: "ASYNC-TIMEOUT";
  /**
   * IDs of the receipts that the message refers to
   */
  ids: ReceiptID[];
  [k: string]: unknown;
}
export interface Notification_CONNDEL {
  type: "CONN-DEL";
  /**
   * IDs of the connections that the message refers to
   */
  ids: ConnectionID[];
  [k: string]: unknown;
}
export interface Notification_OBJDEL {
  type: "OBJ-DEL";
  /**
   * IDs of the objects that the message refers to
   */
  ids: ObjectID[];
  [k: string]: unknown;
}
export interface Notification_SYSCLOSE {
  type: "SYS-CLOSE";
  reason?: string;
  [k: string]: unknown;
}
export interface Notification_SYSMSG {
  type: "SYS-MSG";
  /**
   * @minItems 1
   */
  items: [LogMessage, ...LogMessage[]];
  [k: string]: unknown;
}
/**
 * A single log message sent from the server to the client
 */
export interface LogMessage {
  message: string;
  timestamp?: number;
  sender?: ObjectID;
  severity?: Severity;
  [k: string]: unknown;
}
export interface Request_ASYNCCANCEL {
  type: "ASYNC-CANCEL";
  /**
   * IDs of the receipts that the message refers to
   */
  ids: ReceiptID[];
  [k: string]: unknown;
}
export interface Request_ASYNCRESUME {
  type: "ASYNC-RESUME";
  /**
   * IDs of the receipts that the message refers to
   */
  ids: ReceiptID[];
  values?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Request_AUTHINF {
  type: "AUTH-INF";
}
export interface Request_AUTHREQ {
  type: "AUTH-REQ";
  /**
   * Name of the authentication method to use
   */
  method: string;
  session?: SessionID;
  /**
   * Data to send to the authentication method
   */
  data: string;
  [k: string]: unknown;
}
export interface Request_AUTHWHOAMI {
  type: "AUTH-WHOAMI";
}
export interface Request_BCNINF {
  type: "BCN-INF";
  /**
   * IDs of the beacons that the message refers to
   */
  ids: ObjectID[];
  [k: string]: unknown;
}
export interface Request_BCNPROPS {
  type: "BCN-PROPS";
  /**
   * IDs of the beacons that the message refers to
   */
  ids: ObjectID[];
  [k: string]: unknown;
}
export interface Request_CLKINF {
  type: "CLK-INF";
  /**
   * IDs of the clocks that the message refers to
   */
  ids: ClockID[];
  [k: string]: unknown;
}
export interface Request_CLKLIST {
  type: "CLK-LIST";
}
export interface Request_CONNINF {
  type: "CONN-INF";
  /**
   * IDs of the connections that the message refers to
   */
  ids: ConnectionID[];
  [k: string]: unknown;
}
export interface Request_CONNLIST {
  type: "CONN-LIST";
}
export interface Request_DEVINF {
  type: "DEV-INF";
  /**
   * Paths of the device tree entries that the message refers to
   */
  paths: string[];
  [k: string]: unknown;
}
export interface Request_DEVLIST {
  type: "DEV-LIST";
  /**
   * IDs of the objects that the message refers to
   */
  ids: ObjectID[];
  [k: string]: unknown;
}
export interface Request_DEVLISTSUB {
  type: "DEV-LISTSUB";
  /**
   * Paths of the device tree entries that the message refers to
   */
  pathFilter: string[];
  [k: string]: unknown;
}
export interface Request_DEVSUB {
  type: "DEV-SUB";
  /**
   * Paths of the device tree entries that the message refers to
   */
  paths: string[];
  lazy?: boolean;
  [k: string]: unknown;
}
export interface Request_DEVUNSUB {
  type: "DEV-UNSUB";
  /**
   * Paths of the device tree entries that the message refers to
   */
  paths: string[];
  /**
   * Whether to remove all instances of a subscription that matches one of the paths (true) or only a single one (false)
   */
  removeAll?: boolean;
  /**
   * Whether to also remove all subscriptions that are in the subtrees of the paths specified in the request.
   */
  includeSubtrees?: boolean;
  [k: string]: unknown;
}
export interface Request_DOCKINF {
  type: "DOCK-INF";
  /**
   * IDs of the docking stations that the message refers to
   */
  ids: ObjectID[];
  [k: string]: unknown;
}
export interface Request_EXTCFG {
  type: "EXT-CFG";
  /**
   * IDs of the extensions that the message refers to
   */
  ids: ExtensionID[];
  [k: string]: unknown;
}
export interface Request_EXTINF {
  type: "EXT-INF";
  /**
   * IDs of the extensions that the message refers to
   */
  ids: ExtensionID[];
  [k: string]: unknown;
}
export interface Request_EXTLIST {
  type: "EXT-LIST";
}
export interface Request_EXTLOAD {
  type: "EXT-LOAD";
  /**
   * IDs of the extensions that the message refers to
   */
  ids: ExtensionID[];
  [k: string]: unknown;
}
export interface Request_EXTRELOAD {
  type: "EXT-RELOAD";
  /**
   * IDs of the extensions that the message refers to
   */
  ids: ExtensionID[];
  [k: string]: unknown;
}
export interface Request_EXTSETCFG {
  type: "EXT-SETCFG";
  ids: {
    [k: string]: {
      [k: string]: unknown;
    };
  };
  [k: string]: unknown;
}
export interface Request_EXTUNLOAD {
  type: "EXT-UNLOAD";
  /**
   * IDs of the extensions that the message refers to
   */
  ids: ExtensionID[];
  [k: string]: unknown;
}
export interface Request_FWOBJECTLIST {
  type: "FW-OBJECT-LIST";
  /**
   * IDs of the firmware update targets that a request refers to
   */
  supports?: FirmwareUpdateTargetID[];
  [k: string]: unknown;
}
export interface Request_FWTARGETINF {
  type: "FW-TARGET-INF";
  /**
   * IDs of the firmware update targets that a request refers to
   */
  ids: FirmwareUpdateTargetID[];
  [k: string]: unknown;
}
export interface Request_FWTARGETLIST {
  type: "FW-TARGET-LIST";
  /**
   * IDs of the objects that the message refers to
   */
  supportedBy?: ObjectID[];
  [k: string]: unknown;
}
export interface Request_FWUPLOAD {
  type: "FW-UPLOAD";
  /**
   * IDs of the objects that the message refers to
   */
  ids: ObjectID[];
  target: FirmwareUpdateTargetID;
  blob: string;
  [k: string]: unknown;
}
export interface Request_LCNINF {
  type: "LCN-INF";
  [k: string]: unknown;
}
export interface Request_LOGDATA {
  type: "LOG-DATA";
  uavId: ObjectID;
  logId: FlightLogID;
  [k: string]: unknown;
}
export interface Request_LOGINF {
  type: "LOG-INF";
  /**
   * IDs of the UAVs that the message refers to
   */
  ids: ObjectID[];
  [k: string]: unknown;
}
export interface Request_OBJCMD {
  type: "OBJ-CMD";
  /**
   * IDs of the objects that the message refers to
   */
  ids: ObjectID[];
  /**
   * The command to send
   */
  command: string;
  args?: Arguments;
  kwds?: KeywordArguments;
  [k: string]: unknown;
}
/**
 * Keyword arguments of the command
 */
export interface KeywordArguments {
  [k: string]: unknown;
}
export interface Request_OBJLIST {
  type: "OBJ-LIST";
  /**
   * Types of objects that the user is interested in
   */
  filter?: string[];
}
export interface Request_PRMGET {
  type: "PRM-GET";
  /**
   * IDs of the objects that the message refers to
   */
  ids: ObjectID[];
  /**
   * The name of the parameter
   */
  name: string;
  [k: string]: unknown;
}
export interface Request_PRMSET {
  type: "PRM-SET";
  /**
   * IDs of the objects that the message refers to
   */
  ids: ObjectID[];
  /**
   * The name of the parameter
   */
  name: string;
  [k: string]: unknown;
}
export interface Request_PRMSETMANY {
  type: "PRM-SET-MANY";
  /**
   * IDs of the objects that the message refers to
   */
  ids: ObjectID[];
  parameters: ParameterMap;
  [k: string]: unknown;
}
/**
 * Mapping from parameter names to the corresponding values
 */
export interface ParameterMap {
  [k: string]: unknown;
}
export interface Request_RTKINF {
  type: "RTK-INF";
  /**
   * IDs of the RTK presets that the message refers to
   */
  ids: RTKPresetID[];
  [k: string]: unknown;
}
export interface Request_RTKLIST {
  type: "RTK-LIST";
}
export interface Request_RTKSOURCE {
  type: "RTK-SOURCE";
  /**
   * The ID of the RTK source to use
   */
  id?: string | null;
  [k: string]: unknown;
}
export interface Request_RTKSTAT {
  type: "RTK-STAT";
}
export interface Request_RTKSURVEY {
  type: "RTK-SURVEY";
  settings?: RTKSurveySettings;
  [k: string]: unknown;
}
/**
 * RTK survey settings
 */
export interface RTKSurveySettings {
  /**
   * Minimum duration of RTK survey
   */
  duration: number;
  /**
   * Expected RTK survey position accuracy in meters
   */
  accuracy: number;
  messageSet?: MessageSet;
  position?: ECEFCoordinate;
  gnssTypes?: ("gps" | "glonass" | "galileo" | "sbas" | "qzss" | "beidou" | "irnss")[];
  [k: string]: unknown;
}
export interface Request_SHOWCFG {
  type: "SHOW-CFG";
}
export interface Request_SHOWSETCFG {
  type: "SHOW-SETCFG";
  configuration: DroneShowConfiguration;
  [k: string]: unknown;
}
/**
 * Full configuration of a drone show
 */
export interface DroneShowConfiguration {
  start: StartConditions;
  /**
   * Mapping of show-specific indices to the corresponding UAV IDs, if known. Not mandatory.
   */
  mapping?: (ObjectID | null)[];
  /**
   * The total duration of the show, in seconds. Not mandatory.
   */
  duration?: number;
  [k: string]: unknown;
}
export interface StartConditions {
  /**
   * Whether the server has received authorization from a human operator to start the show
   */
  authorized: boolean;
  authorizationScope?: AuthorizationScope;
  clock: ClockID | null;
  /**
   * Timestamp when the drone show should start
   */
  time: number | null;
  method: "rc" | "auto";
  /**
   * Array containing the IDs of the UAVs that should be started automatically
   */
  uavIds: ObjectID[];
  [k: string]: unknown;
}
export interface Request_SHOWLIGHTS {
  type: "SHOW-LIGHTS";
}
export interface Request_SHOWSETLIGHTS {
  type: "SHOW-SETLIGHTS";
  configuration: DroneLightsConfiguration;
  [k: string]: unknown;
}
/**
 * Full configuration of the behaviour of the LED lights on a drone during a drone show
 */
export interface DroneLightsConfiguration {
  /**
   * Type of the light effect.
   */
  effect?: string;
  /**
   * Color of the light effect in RGB notations. Values in the array must be between 0 and 255, inclusive.
   */
  color?: number[];
  [k: string]: unknown;
}
export interface Request_SYSPING {
  type: "SYS-PING";
  [k: string]: unknown;
}
export interface Request_SYSPORTS {
  type: "SYS-PORTS";
}
export interface Request_SYSTIME {
  type: "SYS-TIME";
  adjustment?: number;
}
export interface Request_SYSVER {
  type: "SYS-VER";
}
export interface Request_UAVCALIB {
  type: "UAV-CALIB";
  /**
   * IDs of the UAVs that the message refers to
   */
  ids: ObjectID[];
  component?: string;
  parameters?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Request_UAVFLY {
  type: "UAV-FLY";
  /**
   * IDs of the UAVs that the message refers to
   */
  ids: ObjectID[];
  target: GPSCoordinate;
  [k: string]: unknown;
}
export interface Request_UAVHALT {
  type: "UAV-HALT";
  /**
   * IDs of the UAVs that the message refers to
   */
  ids: ObjectID[];
  transport?: TransportOptions;
  [k: string]: unknown;
}
/**
 * Additional preferences about how the message should be delivered to UAVs
 */
export interface TransportOptions {
  /**
   * Index of the communication channel to use
   */
  channel?: number;
  /**
   * Stores whether the server is allowed to use a broadcast message
   */
  broadcast?: boolean;
  /**
   * Whether to broadcast the message to all UAVs, ignoring the explicit UAV IDs in the command
   */
  ignoreIds?: boolean;
  [k: string]: unknown;
}
export interface Request_UAVHOVER {
  type: "UAV-HOVER";
  /**
   * IDs of the UAVs that the message refers to
   */
  ids: ObjectID[];
  [k: string]: unknown;
}
export interface Request_UAVINF {
  type: "UAV-INF";
  /**
   * IDs of the UAVs that the message refers to
   */
  ids: ObjectID[];
  [k: string]: unknown;
}
export interface Request_UAVLAND {
  type: "UAV-LAND";
  /**
   * IDs of the UAVs that the message refers to
   */
  ids: ObjectID[];
  transport?: TransportOptions;
  [k: string]: unknown;
}
export interface Request_UAVLIST {
  type: "UAV-LIST";
}
export interface Request_UAVMOTOR {
  type: "UAV-MOTOR";
  /**
   * IDs of the UAVs that the message refers to
   */
  ids: ObjectID[];
  /**
   * Whether the motors should be started or stopped
   */
  start: boolean;
  /**
   * Whether the command should be forced even if it is unsafe
   */
  force?: boolean;
  transport?: TransportOptions;
  [k: string]: unknown;
}
export interface Request_UAVPREFLT {
  type: "UAV-PREFLT";
  /**
   * IDs of the UAVs that the message refers to
   */
  ids: ObjectID[];
  [k: string]: unknown;
}
export interface Request_UAVRST {
  type: "UAV-RST";
  /**
   * IDs of the UAVs that the message refers to
   */
  ids: ObjectID[];
  /**
   * The component to reboot
   */
  component?: string;
  transport?: TransportOptions;
  [k: string]: unknown;
}
export interface Request_UAVRTH {
  type: "UAV-RTH";
  /**
   * IDs of the UAVs that the message refers to
   */
  ids: ObjectID[];
  transport?: TransportOptions;
  [k: string]: unknown;
}
export interface Request_UAVSIGNAL {
  type: "UAV-SIGNAL";
  /**
   * IDs of the UAVs that the message refers to
   */
  ids: ObjectID[];
  signals?: string[];
  duration?: number;
  transport?: TransportOptions;
  [k: string]: unknown;
}
export interface Request_UAVSLEEP {
  type: "UAV-SLEEP";
  /**
   * IDs of the UAVs that the message refers to
   */
  ids: ObjectID[];
  transport?: TransportOptions;
  [k: string]: unknown;
}
export interface Request_UAVTAKEOFF {
  type: "UAV-TAKEOFF";
  /**
   * IDs of the UAVs that the message refers to
   */
  ids: ObjectID[];
  transport?: TransportOptions;
  [k: string]: unknown;
}
export interface Request_UAVTEST {
  type: "UAV-TEST";
  /**
   * IDs of the UAVs that the message refers to
   */
  ids: ObjectID[];
  component?: string;
  parameters?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Request_UAVVER {
  type: "UAV-VER";
  /**
   * IDs of the UAVs that the message refers to
   */
  ids: ObjectID[];
  [k: string]: unknown;
}
export interface Request_UAVWAKEUP {
  type: "UAV-WAKEUP";
  /**
   * IDs of the UAVs that the message refers to
   */
  ids: ObjectID[];
  transport?: TransportOptions;
  [k: string]: unknown;
}
export interface Request_WTHAT {
  type: "WTH-AT";
  position: GPSCoordinate;
  [k: string]: unknown;
}
export interface Request_WTHINF {
  type: "WTH-INF";
  /**
   * IDs of the weather stations that the message refers to
   */
  ids: ObjectID[];
  [k: string]: unknown;
}
export interface Request_WTHLIST {
  type: "WTH-LIST";
}
export interface Response_ACKACK {
  type: "ACK-ACK";
}
export interface Response_ACKNAK {
  type: "ACK-NAK";
  reason?: string;
}
export interface Response_ASYNCCANCEL {
  type: "ASYNC-CANCEL";
  /**
   * IDs of the receipts that the message refers to
   */
  success?: ReceiptID[];
  error?: ErrorMap;
}
export interface ErrorMap {
  [k: string]: string;
}
export interface Response_ASYNCRESUME {
  type: "ASYNC-RESUME";
  /**
   * IDs of the receipts that the message refers to
   */
  success?: ReceiptID[];
  error?: ErrorMap;
}
export interface Response_AUTHINF {
  type: "AUTH-INF";
  methods: string[];
  required: boolean;
  [k: string]: unknown;
}
export interface Response_AUTHRESP_SingleStep {
  type: "AUTH-RESP";
  /**
   * Result of the authentication
   */
  result: boolean;
  /**
   * Explains why the authentication attempt failed
   */
  reason?: string;
  /**
   * Name of the user
   */
  user?: string;
}
export interface Response_AUTHRESP_MultiStep {
  type: "AUTH-RESP";
  /**
   * Data to send to the client that is to be used in the next step of multi-step authentication methods
   */
  data: string;
}
export interface Response_AUTHWHOAMI {
  type: "AUTH-WHOAMI";
  /**
   * Name of the user
   */
  user: string;
  [k: string]: unknown;
}
export interface Response_BCNINF {
  type: "BCN-INF";
  status?: {
    [k: string]: BeaconStatusInfo;
  };
  error?: ErrorMap;
}
/**
 * Status information of a single beacon
 */
export interface BeaconStatusInfo {
  id: ObjectID;
  /**
   * Whether the beacon is currently active (operational). May be omitted for passive beacons or points of interest.
   */
  active?: boolean;
  /**
   * The heading of the beacon in the local tangent plane, in 1/10th of degrees, if known
   */
  heading?: number;
  position?: GPSCoordinate;
  /**
   * Timestamp that denotes when the status of the beacon was updated the last time
   */
  timestamp: number;
  [k: string]: unknown;
}
export interface Response_BCNPROPS {
  type: "BCN-PROPS";
  receipt?: ReceiptMap;
  error?: ErrorMap;
  result?: {
    [k: string]: BeaconBasicProperties;
  };
}
export interface ReceiptMap {
  [k: string]: ReceiptID;
}
/**
 * Basic information of a single beacon that is unlikely to change over time
 */
export interface BeaconBasicProperties {
  id: ObjectID;
  /**
   * The human-readable name of the beacon, shown on the UI
   */
  name: string;
  [k: string]: unknown;
}
export interface Response_CLKINF {
  type: "CLK-INF";
  status?: {
    [k: string]: ClockInfo;
  };
  error?: ErrorMap;
}
/**
 * Information about a clock
 */
export interface ClockInfo {
  id: ClockID;
  epoch?: string | "unix";
  retrievedAt: number;
  running: boolean;
  ticksPerSecond?: number;
  ticks: number;
  [k: string]: unknown;
}
export interface Response_CLKLIST {
  type: "CLK-LIST";
  /**
   * IDs of the clocks that the message refers to
   */
  ids: ClockID[];
}
export interface Response_CONNINF {
  type: "CONN-INF";
  status?: {
    [k: string]: ConnectionInfo;
  };
  error?: ErrorMap;
}
/**
 * Information about a connection
 */
export interface ConnectionInfo {
  id: ConnectionID;
  purpose: Purpose;
  description?: string;
  status: ConnectionStatus;
  timestamp?: number;
  [k: string]: unknown;
}
export interface Response_CONNLIST {
  type: "CONN-LIST";
  /**
   * IDs of the connections that the message refers to
   */
  ids: ConnectionID[];
  [k: string]: unknown;
}
export interface Response_DEVINF {
  type: "DEV-INF";
  values: {
    [k: string]: unknown;
  };
  error?: ErrorMap;
}
export interface Response_DEVLIST {
  type: "DEV-LIST";
  devices?: {
    [k: string]: DeviceTreeNode;
  };
  error?: ErrorMap;
}
/**
 * A single device tree node representing a UAV, a device or a channel
 */
export interface DeviceTreeNode {
  type: DeviceTreeNodeType;
  subType?: ChannelType;
  class?: DeviceClass;
  children?: {
    [k: string]: unknown;
  };
  operations?: ChannelOperation[];
  /**
   * Unit in which the value of a numeric channel is expressed
   */
  unit?: string;
}
export interface Response_DEVLISTSUB {
  type: "DEV-LISTSUB";
  /**
   * Paths of the device tree entries that the message refers to
   */
  paths?: string[];
}
export interface Response_DEVSUB {
  type: "DEV-SUB";
  /**
   * Paths of the device tree entries that the message refers to
   */
  success?: string[];
  error?: ErrorMap;
}
export interface Response_DEVUNSUB {
  type: "DEV-UNSUB";
  /**
   * Paths of the device tree entries that the message refers to
   */
  success?: string[];
  error?: ErrorMap;
}
export interface Response_DOCKINF {
  type: "DOCK-INF";
  status?: {
    [k: string]: DockingStationStatusInfo;
  };
  error?: ErrorMap;
}
/**
 * Status information of a single docking station
 */
export interface DockingStationStatusInfo {
  id: ObjectID;
  position?: GPSCoordinate;
  /**
   * Timestamp that denotes when the status of the docking station was updated the last time
   */
  timestamp: number;
  [k: string]: unknown;
}
export interface Response_EXTCFG {
  type: "EXT-CFG";
  status?: {
    [k: string]: {
      [k: string]: unknown;
    };
  };
  error?: ErrorMap;
}
export interface Response_EXTINF {
  type: "EXT-INF";
  status?: {
    [k: string]: ClockInfo1;
  };
  error?: ErrorMap;
}
/**
 * Information about an extension
 */
export interface ClockInfo1 {
  id: ExtensionID;
  loaded: boolean;
  name: string;
  description?: string;
  [k: string]: unknown;
}
export interface Response_EXTLIST {
  type: "EXT-LIST";
  /**
   * IDs of the extensions that the message refers to
   */
  loaded: ExtensionID[];
  /**
   * IDs of the extensions that the message refers to
   */
  available: ExtensionID[];
}
export interface Response_EXTLOAD {
  type: "EXT-LOAD";
  status?: {
    [k: string]: {
      [k: string]: unknown;
    };
  };
  error?: ErrorMap;
}
export interface Response_EXTRELOAD {
  type: "EXT-RELOAD";
  status?: {
    [k: string]: {
      [k: string]: unknown;
    };
  };
  error?: ErrorMap;
}
export interface Response_EXTSETCFG {
  type: "EXT-SETCFG";
  status?: {
    [k: string]: {
      [k: string]: unknown;
    };
  };
  error?: ErrorMap;
}
export interface Response_EXTUNLOAD {
  type: "EXT-UNLOAD";
  status?: {
    [k: string]: {
      [k: string]: unknown;
    };
  };
  error?: ErrorMap;
}
export interface Response_FWOBJECTLIST {
  type: "FW-OBJECT-LIST";
  /**
   * IDs of the objects that the message refers to
   */
  ids: ObjectID[];
}
export interface Response_FWTARGETINF {
  type: "FW-TARGET-INF";
  result?: {
    [k: string]: FirmwareUpdateTarget;
  };
  error?: ErrorMap;
}
/**
 * A component of an object that can be targeted with a firmware update
 */
export interface FirmwareUpdateTarget {
  id: FirmwareUpdateTargetID;
  name: string;
  [k: string]: unknown;
}
export interface Response_FWTARGETLIST {
  type: "FW-TARGET-LIST";
  /**
   * IDs of the firmware update targets that a request refers to
   */
  ids: FirmwareUpdateTargetID[];
}
export interface Response_FWUPLOAD {
  type: "FW-UPLOAD";
  receipt?: ReceiptMap;
  error?: ErrorMap;
  result?: AsyncCommandResponseMap;
}
export interface AsyncCommandResponseMap {
  [k: string]: CommandResponse | string;
}
/**
 * Response given by a UAV to a command request
 */
export interface CommandResponse {
  type: string;
  data: unknown;
}
export interface Response_LCNINF {
  type: "LCN-INF";
  license: License;
}
/**
 * A license object that is activated on the server
 */
export interface License {
  id: LicenseID;
  version?: number;
  licensee: string;
  expiryDate?: string;
  features?: LicenseFeature[];
  restrictions?: LicenseRestrictions[];
  [k: string]: unknown;
}
/**
 * An optional feature that is enabled by a license
 */
export interface LicenseFeature {
  type: string;
  label?: string;
  secondaryLabel?: string;
  parameters?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Restrictions imposed on the functionality of the server by a license
 */
export interface LicenseRestrictions {
  type: string;
  label?: string;
  secondaryLabel?: string;
  parameters?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Response_LOGDATA {
  type: "LOG-DATA";
  result?: FlightLog;
  error?: string;
  receipt?: ReceiptID;
}
/**
 * Contents of a flight log
 */
export interface FlightLog {
  id: FlightLogID;
  timestamp?: number;
  size?: number;
  kind: FlightLogKind;
  body:
    | string
    | {
        [k: string]: unknown;
      };
  [k: string]: unknown;
}
export interface Response_LOGINF {
  type: "LOG-INF";
  result?: {
    /**
     * List of the metadata of flight logs stored on a UAV
     */
    [k: string]: FlightLogMetadata[];
  };
  error?: ErrorMap;
  receipt?: ReceiptMap;
}
/**
 * Metadata of a single flight log entry stored on a UAV
 */
export interface FlightLogMetadata {
  id: FlightLogID;
  timestamp?: number;
  size?: number;
  kind: FlightLogKind;
  [k: string]: unknown;
}
export interface Response_OBJCMD {
  type: "OBJ-CMD";
  receipt?: ReceiptMap;
  error?: ErrorMap;
  result?: AsyncCommandResponseMap;
}
export interface Response_OBJLIST {
  type: "OBJ-LIST";
  /**
   * IDs of the objects that the message refers to
   */
  ids: ObjectID[];
}
export interface Response_PRMGET {
  type: "PRM-GET";
  result?: {
    [k: string]: unknown;
  };
  error?: ErrorMap;
  receipt?: ReceiptMap;
}
export interface Response_PRMSET {
  type: "PRM-SET";
  result?: BoolMap;
  error?: ErrorMap;
  receipt?: ReceiptMap;
}
export interface BoolMap {
  [k: string]: boolean;
}
export interface Response_PRMSETMANY {
  type: "PRM-SET-MANY";
  result?: {
    [k: string]: {
      success: boolean;
      failed?: string[];
      [k: string]: unknown;
    };
  };
  error?: ErrorMap;
  receipt?: ReceiptMap;
}
export interface Response_RTKINF {
  type: "RTK-INF";
  preset: {
    [k: string]: RTKConfigurationPreset;
  };
  error?: ErrorMap;
}
/**
 * Information about an RTK preset
 */
export interface RTKConfigurationPreset {
  /**
   * A human-readable title of the preset
   */
  title: string;
  type?: RTKPresetType;
  format: MessageFormat;
  /**
   * List of source connections where this preset collects messages from
   */
  sources: string[];
  [k: string]: unknown;
}
export interface Response_RTKLIST {
  type: "RTK-LIST";
  /**
   * IDs of the RTK presets that the message refers to
   */
  ids: RTKPresetID[];
}
export interface Response_RTKSOURCE {
  type: "RTK-SOURCE";
  /**
   * The ID of the RTK source used
   */
  id: string | null;
}
export interface Response_RTKSTAT {
  type?: "RTK-STAT";
  antenna: RTKAntennaInfo;
  messages: {
    [k: string]: RTKMessageObservations;
  };
  messages_tx?: {
    [k: string]: RTKMessageObservations;
  };
  cnr: {
    /**
     * RTK satellite carrier-to-noise ratios in dB
     */
    [k: string]: number;
  };
  survey: RTKSurveyStatus;
}
/**
 * Information about an RTK antenna
 */
export interface RTKAntennaInfo {
  stationId?: StationID;
  descriptor?: string;
  serialNumber?: string;
  position?: GPSCoordinate;
  positionECEF?: ECEFCoordinate;
  [k: string]: unknown;
}
/**
 * RTK survey accuracy and flags
 */
export interface RTKSurveyStatus {
  /**
   * RTK survey position accuracy in meters
   */
  accuracy: number;
  /**
   * RTK survey status flags (0: unknown, 1: supported, 2: active, 4: valid)
   */
  flags: number;
  [k: string]: unknown;
}
export interface Response_RTKSURVEY {
  type: "RTK-SURVEY";
  settings: RTKSurveySettings;
}
export interface Response_SHOWCFG {
  type: "SHOW-CFG";
  configuration: DroneShowConfiguration;
  [k: string]: unknown;
}
export interface Response_SHOWLIGHTS {
  type: "SHOW-LIGHTS";
  configuration: DroneLightsConfiguration;
  [k: string]: unknown;
}
export interface Response_SYSPORTS {
  type: "SYS-PORTS";
  ports: ServicePortMap;
  [k: string]: unknown;
}
/**
 * Mapping of services offered by the server to the corresponding ports
 */
export interface ServicePortMap {
  [k: string]: number;
}
export interface Response_SYSTIME {
  type: "SYS-TIME";
  timestamp: number;
  [k: string]: unknown;
}
export interface Response_SYSVER {
  type: "SYS-VER";
  name?: string;
  software: string;
  /**
   * Version number in major.minor.patch format; minor and patch versions are optional
   */
  version: string;
  revision?: string;
  [k: string]: unknown;
}
export interface Response_UAVCALIB {
  type: "UAV-CALIB";
  result?: BoolMap;
  error?: ErrorMap;
  receipt?: ReceiptMap;
}
export interface Response_UAVFLY {
  type: "UAV-FLY";
  result?: BoolMap;
  error?: ErrorMap;
  receipt?: ReceiptMap;
}
export interface Response_UAVHALT {
  type: "UAV-HALT";
  result?: BoolMap;
  error?: ErrorMap;
  receipt?: ReceiptMap;
}
export interface Response_UAVHOVER {
  type: "UAV-HOVER";
  result?: BoolMap;
  error?: ErrorMap;
  receipt?: ReceiptMap;
}
export interface Response_UAVINF {
  type: "UAV-INF";
  status?: {
    [k: string]: UAVStatusInfo;
  };
  error?: ErrorMap;
}
/**
 * Status information of a single UAV
 */
export interface UAVStatusInfo {
  id: ObjectID;
  /**
   * The flight mode of the UAV
   */
  mode?: string;
  position?: GPSCoordinate;
  positionXYZ?: PositionXYZ;
  gps?: GPSFix;
  /**
   * The heading of the UAV in the local tangent plane, in 1/10th of degrees
   */
  heading?: number;
  attitude?: Attitude;
  velocity?: VelocityNED;
  velocityXYZ?: VelocityXYZ;
  /**
   * Timestamp that denotes when the status of the UAV was updated the last time
   */
  timestamp: number;
  battery?: BatteryInformation;
  /**
   * Color in RGB565 representation
   */
  light?: number;
  /**
   * Received signal strength indicator, for each of the channels the UAV is accessible on
   */
  rssi?: number[];
  /**
   * List of currently active error codes for a single UAV
   */
  errors?: number[];
  debug?: string;
  [k: string]: unknown;
}
export interface Response_UAVLAND {
  type: "UAV-LAND";
  result?: BoolMap;
  error?: ErrorMap;
  receipt?: ReceiptMap;
}
export interface Response_UAVLIST {
  type: "UAV-LIST";
  /**
   * IDs of the UAVs that the message refers to
   */
  ids: ObjectID[];
  [k: string]: unknown;
}
export interface Response_UAVMOTOR {
  type: "UAV-MOTOR";
  result?: BoolMap;
  error?: ErrorMap;
  receipt?: ReceiptMap;
}
export interface Response_UAVPREFLT {
  type: "UAV-PREFLT";
  status?: {
    [k: string]: UAVPreflightCheckInfo;
  };
  error?: ErrorMap;
}
/**
 * Preflight check information of a single UAV
 */
export interface UAVPreflightCheckInfo {
  items: ASingleItemInAPreflightChecklist[];
  /**
   * Preflight check summary message
   */
  message?: string;
  result: PreflightCheckResult;
  [k: string]: unknown;
}
export interface ASingleItemInAPreflightChecklist {
  id: ObjectID;
  label?: string;
  result: PreflightCheckResult;
  message?: string;
  [k: string]: unknown;
}
export interface Response_UAVRST {
  type: "UAV-RST";
  result?: BoolMap;
  error?: ErrorMap;
  receipt?: ReceiptMap;
}
export interface Response_UAVRTH {
  type: "UAV-RTH";
  result?: BoolMap;
  error?: ErrorMap;
  receipt?: ReceiptMap;
}
export interface Response_UAVSIGNAL {
  type: "UAV-SIGNAL";
  result?: BoolMap;
  error?: ErrorMap;
  receipt?: ReceiptMap;
}
export interface Response_UAVSLEEP {
  type: "UAV-SLEEP";
  result?: BoolMap;
  error?: ErrorMap;
  receipt?: ReceiptMap;
}
export interface Response_UAVTAKEOFF {
  type: "UAV-TAKEOFF";
  result?: BoolMap;
  error?: ErrorMap;
  receipt?: ReceiptMap;
}
export interface Response_UAVTEST {
  type: "UAV-TEST";
  result?: BoolMap;
  error?: ErrorMap;
  receipt?: ReceiptMap;
}
export interface Response_UAVVER {
  type: "UAV-VER";
  result?: {
    [k: string]: VersionMap;
  };
  error?: ErrorMap;
  receipt?: ReceiptMap;
}
/**
 * Object mapping string identifiers to version numbers in no particular format
 */
export interface VersionMap {
  [k: string]: string;
}
export interface Response_UAVWAKEUP {
  type: "UAV-WAKEUP";
  result?: BoolMap;
  error?: ErrorMap;
  receipt?: ReceiptMap;
}
export interface Response_WTHAT {
  type: "WTH-AT";
  weather?: WeatherInfo;
}
export interface WeatherInfo {
  stationId?: ObjectID;
  position: GPSCoordinate;
  /**
   * Timestamp that denotes the time the weather information applies to
   */
  timestamp: number;
  /**
   * Numeric weather condition code according to OpenWeatherMap conventions
   */
  code?: number;
  /**
   * Time of sunrise; negative if the Sun does not rise on the given day
   */
  sunrise?: number;
  /**
   * Time of sunset; negative if the Sun does not set on the given day
   */
  sunset?: number;
  /**
   * Temperature, in kelvin
   */
  temperature?: number;
  /**
   * Temperature, in kelvin, adjusted for human perception of weather
   */
  feelsLike?: number;
  /**
   * Atmospheric pressure on the sea level, in Pa
   */
  pressure?: number;
  /**
   * Humidity, in %
   */
  humidity?: number;
  /**
   * Atmospheric temperature in 1/10th kelvin below which water droplets begin to condense and dew can form
   */
  dewPoint?: number;
  /**
   * Cloudiness, in %
   */
  clouds?: number;
  /**
   * UV index, 1/100 units; e.g. 89 --> 0.89
   */
  uvIndex?: number;
  kpIndex?: number;
  magneticVector?: MagneticVector;
  /**
   * Average visibility, in metres
   */
  visibility?: number;
  /**
   * Meteorological wind direction, in 1/10th degrees clockwise from due North
   */
  windDirection?: number;
  /**
   * Wind speed, in mm/s
   */
  windSpeed?: number;
  /**
   * Wind gust, in mm/s
   */
  windGust?: number;
  [k: string]: unknown;
}
export interface Response_WTHINF {
  type: "WTH-INF";
  status?: {
    [k: string]: WeatherInfo;
  };
  error?: ErrorMap;
}
export interface Response_WTHLIST {
  type: "WTH-LIST";
  /**
   * IDs of the weather stations that the message refers to
   */
  ids: ObjectID[];
}
export interface ErrorMessage {
  /**
   * Version number in major.minor.patch format; minor and patch versions are optional
   */
  "$fw.version": string;
  id: MessageID;
  refs?: MessageID;
  error: {
    code?: number;
    message?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
