= `ACK` — Acknowledgment messages

The messages in this section are always used as responses; no request is
ever sent with these message types.

[#ack-ack]
== `ACK-ACK` — Positive acknowledgment

Sent by the server to the client in response to requests that have been
executed successfully and where it is not necessary for the response to
convey any more detailed information.

*Response fields*

This response has no fields.

*Example response*

[source,json]
----
{
    "type": "ACK-ACK"
}
----

[#ack-nak]
== `ACK-NAK` — Negative acknowledgment

Sent by the server to the client in response to requests that the server
has either attempted to execute but failed to do so, or to requests that
have been rejected outright by the server.

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`reason` |no |string |Human-readable description of the reason for the
negative acknowledgment.
|===

*Example response*

[source,json]
----
{
    "type": "ACK-NAK",
    "reason": "I'm sorry, Dave, I'm afraid I can't do that."
}
----
