= `BCN` — Beacon-related messages

Beacons are subtypes of objects and thus exist in the same namespace as
all other objects in the server. The messages listed in this section are specific
to beacons and do not apply to other object types.

== `BCN-INF` - Basic status information of one or more beacons

A client sends this request to the server to obtain basic status
information about one or more beacons currently known to the server.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of beacon IDs that the client is
interested in
|===

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`status` |no |object of xref:types.adoc#_beaconstatusinfo[`BeaconStatusInfo`] |Object mapping beacon IDs to the corresponding
status information.

|`error` |no |object |Object mapping beacon IDs to reasons why the
corresponding status information could not have been retrieved.
|===

All the beacon IDs that were specified in the request MUST appear
_either_ in the `status` list or in the `error` map.

*Example request*

[source,json]
----
{
    "type": "BCN-INF",
    "ids": ["base", "spam"]
}
----

*Example response*

[source,json]
----
{
    "type": "BCN-INF",
    "status": {
        "base": {
            "id": "base",
            "position": [519976597, -7406863, 93765],
            "timestamp": "2015-12-08T08:17:41.000Z",
            "heading": 290,
            "active": true
        }
    },
    "error": {
        "spam": "No such beacon."
    }
}
----

== `BCN-PROPS` - Basic properties of one or more beacons

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of beacon IDs that the client is
interested in
|===

*Response fields*

The response is a xref:async.adoc#multi-async-response[multi-object async response];
each beacon ID is mapped to the basic properties of the beacon as a
xref:types.adoc#beacon-basic-properties[BeaconBasicProperties] object.

*Example request*

[source,json]
----
{
    "type": "BCN-PROPS",
    "ids": ["base", "spam"]
}
----

*Example response*

[source,json]
----
{
    "type": "BCN-PROPS",
    "result": {
        "base": {
            "id": "base",
            "name": "Main base"
        }
    },
    "error": {
        "spam": "No such beacon."
    }
}
----
