= `CMD` — Command execution

Commands are typically executed on UAVs in an asynchronous manner. Commands
may include landing or takeoff requests, navigation commands, shutdown requests
and many other things. Other objects (e.g., docking stations) may also implement
a command set. In this section, we will refer to the object that a command is
being sent to as the _target_ of the command.

[#cmd-inf]
== `CMD-INF` — Retrieve execution status of a command

A client sends this request to the server to retrieve the execution
status of one or more command requests dispatched earlier.

The execution of a command has the following stages:

* First, the command is _sent_ by the server to the targeted object (UAV,
  docking station etc).
* Next, the receipt of the command MAY be _acknowledged_ by the target.
* After an optional acknowledgment, the UAV starts the actual execution
of the command.
* During the execution, the target MAY post _progress updates_ to the
server.
* Finally, the execution of the command is _finished_ on the target and the
response is sent back to the server.

The time when the request is sent to the target is stored by the server and
returned in the execution status record. The time when the server
receives an acknowledgment is also recorded, as well as the time when
the last progress update was received. Finally, when the command
finishes execution, the date when the execution was finished is also
recorded by the server.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of receipts for the command
execution requests that the client is interested in
|===

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`status` |no |xref:types.adoc#_commandexecutionstatus[`CommandExecutionStatus`] |Object mapping receipts to the corresponding status information.

|`failure` |no |list of strings |List containing the connection IDs for
which the status information could not have been retrieved.

|`reasons` |no |object |Object mapping connection IDs to reasons why the
corresponding status information could not have been retrieved.
|===

All the receipts that were specified in the request MUST appear _either_
as keys in the `status` object or in the `failure` list.

*Example request*

[source,json]
----
{
    "type": "CMD-INF",
    "ids": [
        "0badcafe-deadbeef:1",
        "0badcafe-deadbeef:3"
    ]
}
----

*Example response*

[source,json]
----
{
    "type": "CMD-INF",
    "status": {
        "0badcafe-deadbeef:1": {
            "sent": 1459670842000,
            "acknowledged": 1459670842471,
            "updated": 1459670842811,
            "progress": 80,
        }
    },
    "failure": ["0badcafe-deadbeef:3"],
    "reasons": {
        "0badcafe-deadbeef:3": "No such receipt"
    }
}
----

== `CMD-REQ` — Send a command execution request to a target

A client sends this request to the server to ask the server to forward a
command to one or more targets. The interpretation of the command string
depends entirely on the target; for instance, a UAV running our `flockctrl`
software will accept `flockctrl` console commands and respond
appropriately. The server merely acts as a forwarder between the client
and the target.

Depending on the protocol that the target speaks, it may accept a
raw command string only, or a command string with positional and/or
keyword arguments. Positional arguments are passed as a single array.
Keyword arguments are passed as a JSON object that maps the names of the
arguments to their values. It is the responsibility of the caller to
ensure that the command and its arguments use the appropriate syntax.

Sending and executing a command typically takes some time (especially
because there is usually a slower radio link involved between the ground
station and the target). To keep things running smoothly, the server will
not wait for the responses of the targets to arrive - it will respond with
a `CMD-REQ` response packet as soon as it has attempted to send the
command to all the targets. The response packet will list the IDs of the
targets for which the transmission failed, as well as a mapping that maps
the IDs of the targets for which the command was sent successfully to
unique _receipts_ that can be used by the client to retrieve the
progress of execution for these commands using a
<<cmd-inf,CMD-INF>> command.
The actual response of a command request (sent by a target) will
be relayed back to the client that initiated the command in a
<<cmd-resp,CMD-RESP>> notification.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of object IDs that the command
should be sent to

|`command` |yes |string |The command to send to the objects

|`args` |no |array |The positional arguments of the command

|`kwds` |no |object |The keyword arguments of the command
|===

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`receipts` |no |object |Object that maps the object IDs for which the
command was sent successfully to the corresponding receipts that can be
used to track the progress of execution of the command until the actual
response is received. Each receipt is a string; its format is
unspecified and it is the responsibility of the server to ensure its
uniqueness.

|`failure` |no |list of strings |List containing the object IDs for which
the status information could not have been retrieved.

|`reasons` |no |object |Mapping from object IDs to reasons why the
corresponding status information could not have been retrieved.
|===

All the connection IDs that were specified in the request MUST appear
_either_ in the `receipts` mapping as keys or in the `failure` list.

*Example request*

[source,json]
----
{
    "type": "CMD-REQ",
    "ids": ["1", "17", "31", "spam"],
    "command": "algo"
}
----

*Example response*

[source,json]
----
{
    "type": "CMD-REQ",
    "receipts": {
        "1": "0badcafe-deadbeef:1",
        "17": "0badcafe-deadbeef:2"
    },
    "failure": ["31", "spam"],
    "reasons": {
        "31": "Command execution not supported.",
        "spam": "No such object."
    }
}
----

[#cmd-resp]
== `CMD-RESP` — Response to a command request

A server sends a notification of this type to a client when an earlier
command execution request sent by the client has been completed by one
of the objects the request was targeted to.

In the simplest case, the server responds to a command request with a
string. In more complex cases, the server may return an object of type
xref:types.adoc#_commandresponse[`CommandResponse`], which is basically
an arbitrary object along with a type field that describes how the
object should be interpreted.

*Notification fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`id` |yes |string |The receipt identifier that tells the client which
response is being relayed in this notification.

|`response` |yes |string or
xref:types.adoc#_commandresponse[`CommandResponse`] |The response sent
by the target.
|===

*Example notification: plain text response*

[source,json]
----
{
    "type": "CMD-RESP",
    "id": "0badcafe-deadbeef:1",
    "response": "Hello there!"
}
----

*Example notification: Markdown-formatted response*

[source,json]
----
{
    "type": "CMD-RESP",
    "id": "0badcafe-deadbeef:1",
    "response": {
        "type": "markdown",
        "data": "# Heading\nHello there!"
    }
}
----

*Example notification: complex object*

[source,json]
----
{
    "type": "CMD-RESP",
    "id": "0badcafe-deadbeef:1",
    "response": {
        "type": "markdown",
        "data": {
            "meaning_of_life": 42
        }
    }
}
----

== `CMD-TIMEOUT` — Command request timeout notification

A server sends a notification of this type to a client when an earlier
command execution request sent by the client has timed out (i.e. the object
the command was targeted to failed to return a response in time).

*Notification fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of receipts for the command
execution requests that have timed out
|===

*Example notification*

[source,json]
----
{
    "type": "CMD-TIMEOUT",
    "ids": ["0badcafe-deadbeef:1", "0badcafe-deadbeef:2"]
}
----
