= `DOCK` — Docking station related messages

Docking stations are subtypes of objects and thus exist in the same namespace as
all other objects in the server. The messages listed in this section are specific
to docking stations and do not apply to other object types.

== `DOCK-INF` - Basic status information of one or more docking stations.

A client sends this request to the server to obtain basic status
information about one or more docking stations currently known to the server.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of dock IDs that the client is
interested in
|===

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`status` |no |object of xref:types.adoc#_dockstatusinfo[`DockStatusInfo`] |Object mapping docking station IDs to the corresponding
status information.

|`failure` |no |list of strings |List containing the docking station IDs for which
the status information could not have been retrieved.

|`reasons` |no |object |Object mapping docking station IDs to reasons why the
corresponding status information could not have been retrieved.
|===

All the docking station IDs that were specified in the request MUST appear
_either_ in the `status` list or in the `failure` list.

*Example request*

[source,json]
----
{
    "type": "DOCK-INF",
    "ids": ["base", "spam"]
}
----

*Example response*

[source,json]
----
{
    "type": "DOCK-INF",
    "status": {
        "base": {
            "id": "base",
            "position": {
                "lat": 51.9976597,
                "lon": -0.7406863,
                "amsl": 93.765
            },
            "timestamp": "2015-12-08T08:17:41.000Z"
        }
    },
    "failure": ["spam"],
    "reasons": {
        "spam": "No such dock."
    }
}
----
