= `EXT` — Management of extension modules

Flockwave server implementations may be built in a modular manner such that
certain parts of its functionality are provided by extension modules. Messages
in this group provide facilities for loading, unloading and reconfiguring
extensions.

Note that Flockwave server implementations MUST provide handlers for these
messages even if the server itself does not provide extensions. In such
cases, requests for the list of extensions MUST return an empty list, and
all other messages referring to specific extensions can simply return an
error code.

== `EXT-CFG` - Retrieve the current configuration of extensions

A client sends this request to the server to obtain information about the configuration
of extensions with IDs specified in the request.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` | yes | list of strings| The list of extension IDs whose configuration the client requests.
|===

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`status` | no |object | Object that contains the configuration for each
requested extension ID.
|`error` | no | object | Object mapping extension IDs to error messages
about why the request failed for these IDs.
|===

*Example request*

[source,json]
----
include::example$request_EXT-CFG.json[]
----

*Example response*

[source,json]
----
include::example$response_EXT-CFG.json[]
----

== `EXT-INF` - Retrieve details about an extension

A client sends this request to the server to obtain the details
of the extensions with IDs specified in the request.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` | yes | list of strings| The list of extension IDs whose details the client requests.
|===

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`status` | no |object | Object that contains the available information
for each requested extension ID. The structure of this object is described
by the xref:types.adoc#_extensioninfo[`ExtensionInfo`] complex type.
|`error` | no | object | Object mapping extension IDs to error messages
about why the request failed for these IDs.
|===

*Example request*

[source,json]
----
include::example$request_EXT-INF.json[]
----

*Example response*

[source,json]
----
include::example$response_EXT-INF.json[]
----

== `EXT-LIST` — List of loaded and unloaded extensions

A client sends this request to the server to retrieve the list of extensions
that are currently loaded as well as the list of extensions that are not
loaded but could be loaded.

*Request fields*

This request has no fields.

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`loaded` |yes |list of strings |List containng the identifiers of the extensions that are currently loaded and used by the server

|`available` |yes |list of strings |List containng the identifiers of the extensions that are currently not loaded by the server but could be loaded upon request

|===

*Example request*

[source,json]
----
include::example$request_EXT-LIST.json[]
----

*Example response*

[source,json]
----
include::example$response_EXT-LIST.json[]
----

== `EXT-LOAD` - Load an extension

A client sends this request to the server to load the extensions with IDs specified
in the request.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` | yes | list of strings| The list of extension IDs which the client requests to load.
|===

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`status` | no |object | Object that contains empty objects for
each requested extension that was successfully loaded.
|`error` | no | object | Object mapping extension IDs to error messages
about why the request failed for these IDs.
|===

*Example request*

[source,json]
----
include::example$request_EXT-LOAD.json[]
----

*Example response*

[source,json]
----
include::example$response_EXT-LOAD.json[]
----

== `EXT-RELOAD` - Reload an extension

A client sends this request to the server to reload the extensions with IDs specified
in the request.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` | yes | list of strings| The list of extension IDs which the client requests to reload.
|===

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`status` | no |object | Object that contains empty objects for
each requested extension that was successfully reloaded.
|`error` | no | object | Object mapping extension IDs to error messages
about why the request failed for these IDs.
|===

*Example request*

[source,json]
----
include::example$request_EXT-RELOAD.json[]
----

*Example response*

[source,json]
----
include::example$response_EXT-RELOAD.json[]
----

== `EXT-SETCFG` - Set the current configuration of extensions

A client sends this request to the server to set the desired configuration
for extensions with IDs specified in the request.

It should be noted, that the new configuration values do NOT take effect
until the affected extensions are reloaded.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` | yes |object | Object that specifies new configuration values
for each extension identified by their respective IDs.
|===

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`status` | no |object | Object that contains empty objects for
each requested extension that was successfully configured.
|`error` | no | object | Object mapping extension IDs to error messages
about why the request failed for these IDs.
|===

*Example request*

[source,json]
----
include::example$request_EXT-SETCFG.json[]
----

*Example response*

[source,json]
----
include::example$response_EXT-SETCFG.json[]
----

== `EXT-UNLOAD` - Unload an extension

A client sends this request to the server to unload the extensions with IDs specified
in the request.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` | yes | list of strings| The list of extension IDs which the client requests to unload.
|===

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`status` | no |object | Object that contains empty objects for
each requested extension that was successfully unloaded.
|`error` | no | object | Object mapping extension IDs to error messages
about why the request failed for these IDs.
|===

*Example request*

[source,json]
----
include::example$request_EXT-UNLOAD.json[]
----

*Example response*

[source,json]
----
include::example$response_EXT-UNLOAD.json[]
----
