= `EXT` — Management of extension modules

Flockwave server implementations may be built in a modular manner such that
certain parts of its functionality are provided by extension modules. Messages
in this group provide facilities for loading, unloading and reconfiguring
extensions.

Note that Flockwave server implementations MUST provide handlers for these
messages even if the server itself does not provide extensions. In such
cases, requests for the list of extensions MUST return an empty list, and
all other messages referring to specific extensions can simply return an
error code.

== `EXT-CFG` - Retrieve the current configuration of extensions

#TODO: document me!#

*Example request*

[source,json]
----
include::example$request_EXT-CFG.json[]
----

*Example response*

[source,json]
----
include::example$response_EXT-CFG.json[]
----

== `EXT-INF` - Retrieve details about an extension

#TODO: document me!#

*Example request*

[source,json]
----
include::example$request_EXT-INF.json[]
----

*Example response*

[source,json]
----
include::example$response_EXT-INF.json[]
----

== `EXT-LIST` — List of loaded and unloaded extensions

A client sends this request to the server to retrieve the list of extensions
that are currently loaded as well as the list of extensions that are not
loaded but could be loaded.

*Request fields*

This request has no fields.

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`loaded` |yes |list of strings |List containng the identifiers of the extensions that are currently loaded and used by the server

|`available` |yes |list of strings |List containng the identifiers of the extensions that are currently not loaded by the server but could be loaded upon request

|===

*Example request*

[source,json]
----
include::example$request_EXT-LIST.json[]
----

*Example response*

[source,json]
----
include::example$response_EXT-LIST.json[]
----

== `EXT-LOAD` - Load an extension

#TODO: document me!#

*Example request*

[source,json]
----
include::example$request_EXT-LOAD.json[]
----

*Example response*

[source,json]
----
include::example$response_EXT-LOAD.json[]
----

== `EXT-RELOAD` - Reload an extension

#TODO: document me!#

*Example request*

[source,json]
----
include::example$request_EXT-RELOAD.json[]
----

*Example response*

[source,json]
----
include::example$response_EXT-RELOAD.json[]
----

== `EXT-SETCFG` - Set the current configuration of extensions

#TODO: document me!#

*Example request*

[source,json]
----
include::example$request_EXT-SETCFG.json[]
----

*Example response*

[source,json]
----
include::example$response_EXT-SETCFG.json[]
----

== `EXT-UNLOAD` - Unload an extension

#TODO: document me!#

*Example request*

[source,json]
----
include::example$request_EXT-UNLOAD.json[]
----

*Example response*

[source,json]
----
include::example$response_EXT-UNLOAD.json[]
----
