= `OBJ` — Generic object-related messages

== `OBJ-DEL` - Object removal notification

A server sends a notification of this type to a client when an existing object
(UAV, docking station, beacon etc) was removed from the server, typically
due to inactivity.

*Notification fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of objects that were removed
|===

*Example notification*

[source,json]
----
{
    "type": "OBJ-DEL",
    "ids": ["dock-01"]
}
----

== `OBJ-LIST` — List of objects known by the server

A client sends this request to the server to request the list of all objects
(UAVs, docking stations, beacons etc) currently known to the server. The
semantics of ``knowing'' an object is left up to the server implementation
and configuration; typically, the server will consider an object to be "known"
if it has received a status message from the object recently, typically in the
last few minutes. Other objects may be considered to be known permanently;
for instance, a server pre-filled with a list of weather stations around a
country may simply return these as active objects even though it is not receiving
any explicit updates from them.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`filter` |no |list of xref:types.adoc#_objecttype[ObjectType] |The list of object types that the caller is interested in; default is all object types
|===

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of object IDs that the server knows
|===

*Example request*

[source,json]
----
{
    "type": "OBJ-LIST",
    "filter": ["uav"]
}
----

*Example response*

[source,json]
----
{
    "type": "OBJ-LIST",
    "ids": ["1", "17", "31"]
}
----
