= `RTK` — Real Time Kinematics related messages

Flockwave servers may manage Real Time Kinematics (RTK) corrections;
these corrections may be received from an RTK-capable GNSS based
station, can be displayed on the user interface in a Flockwave client
or may be broadcast to UAVs in the range of the Flockwave server for
enahncing GNSS positioning accuracy.

RTK based stations need to be configured before use with either a
fixed known position or with initiating an auto survey to measure its
own location accurately. Base stations will start to send correction
signals to UAVs only when they have acquired a known position.

RTK base stations are identified by unique string identifiers (just
like objects or connections). These may include RTK presets from a
remote NTRIP source or local base stations connected through e.g. a
serial port.


== `RTK-INF` — Retrieve status of an RTK preset

A client sends this request to the server to retrieve the status of one
or more RTK presets (base stations) managed by the server.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of RTK preset IDs that the client is
interested in
|===

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`preset` |no |object |Object mapping RTK preset IDs to the corresponding
status information. The structure of this object is described by the
xref:types.adoc#rtk-preset-info[`RTKConfigurationPreset`] complex type.

|`error` |no |object |Object mapping RTK preset IDs to reasons why the
corresponding status information could not have been retrieved.
|===

All the RTK preset IDs that were specified in the request MUST appear
_either_ as keys in the `status` object or in the `error` map.

*Example request*

[source,json]
----
include::example$request_RTK-INF.json[]
----

*Example response*

[source,json]
----
include::example$response_RTK-INF.json[]
----


== `RTK-LIST` — List of all the RTK presets managed by the server

A client sends this request to the server to obtain the list of all the
RTK presets currently managed by the server.

*Request fields*

This request has no fields.

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of RTK preset IDs for all the RTK
base stations that the server manages
|===

*Example request*

[source,json]
----
include::example$request_RTK-LIST.json[]
----

*Example response*

[source,json]
----
include::example$response_RTK-LIST.json[]
----


== `RTK-STAT` — Status information about the RTK base managed by the server

A client sends this request to the server to obtain statistical information of
the RTK base station operation currently managed by the server.

*Request fields*

This request has no fields.

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`antenna` |yes |object |Object holding information about the current RTK antenna.
The structure of this object is described by the
xref:types.adoc#rtk-antenna-info[`AntennaInformation`] complex type.

|`messages` |yes |object |Object holding statistical information about RTK messages
sent. The structure of this object is described by the
xref:types.adoc#rtk-message-observations[`MessageObservations`] complex type.

|`cnr` |yes |object |Object holding information about the satellite carrier-to-noise
ratios. The object is indexed by the names of the seen satellites and each value
contains the corresponding latest carrier-to-noise value in decibels (dB).

|`survey` |yes |object |Object holding information about the status of the current
RTK survey procedure. The structure of this object is described by the
xref:types.adoc#rtk-survey-status[`SurveyStatus`] complex type.

|===

*Example request*

[source,json]
----
include::example$request_RTK-STAT.json[]
----

*Example response*

[source,json]
----
include::example$response_RTK-STAT.json[]
----


== `RTK-SOURCE` — Select an RTK source managed by the server

A client sends this request to the server to select an RTK preset
that will be used as the active RTK base station that sends RTK corrections
to the UAVs through the server.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`id` |yes |string |The ID of the RTK preset to use
|===

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`id` |yes |string |The ID of the RTK preset selected as RTK base
|===

*Example request*

[source,json]
----
include::example$request_RTK-SOURCE.json[]
----

*Example response*

[source,json]
----
include::example$response_RTK-SOURCE.json[]
----


== `RTK-SURVEY` — Start an RTK survey with the currently used RTK base station

A client sends this request to the server to instruct the currently selected
RTK base station to either to start an RTK auto-survey to measure its own position, or to set its position explicitly.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`settings` |no |object |Object holding information about the required settings
of the RTK survey procedure. The structure of this object is described by the
xref:types.adoc#rtk-survey-settings[`RTKSurveySettings`] complex type.
|===

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`settings` |no |object |Object holding information about the actual settings
of the RTK survey procedure. The structure of this object is described by the
xref:types.adoc#rtk-survey-settings[`RTKSurveySettings`] complex type.
|===

*Example request*

[source,json]
----
include::example$request_RTK-SURVEY.json[]
----

*Example response*

[source,json]
----
include::example$response_RTK-SURVEY.json[]
----
