= `SHOW` — Management and execution of drone shows

The messages in this section are used to get or set the configuration of
both the drone show and the LED lights on the drones.

== `SHOW-CFG` - Retrieve the current configuration of the drone show

A client sends this request to the server to obtain information about
the configuration of the drone show.

The server response contains an object of type xref:types.adoc#_droneshowconfiguration[`DroneShowConfiguration`],
which for example can contain information about whether the show is authorized to start, the timestamp when the
drone show should start, the identifier of the clock that the start time refers to and more.

*Request fields*

This request has no fields.

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`configuration` | yes | Object of type xref:types.adoc#_droneshowconfiguration[`DroneShowConfiguration`]| Full configuration of a drone show
|===

*Example request*

[source,json]
----
include::example$request_SHOW-CFG.json[]
----

*Example response*

[source,json]
----
include::example$response_SHOW-CFG.json[]
----


== `SHOW-CRTH-PLAN` - Generate collective return-to-home plans for a drone show

A client sends a `.skyc` show file to the server and requests the generation of
collective RTH (return-to-home) plans for it. These plans are alternative
endings of a show at different timestamps that can be triggered adaptively
on-site, allowing the operator to cancel the show mid-flight in an organized
manner where drones return on collision-free paths.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`show` |yes |string |Base64-encoded `.skyc` show file to generate collective RTH plans for

|`preferred_distance` |no |float |Preferred distance between drones during collective RTH, in meters. If not specified, a default value of 5 meters will be used.

|`min_distance` |no |float |Minimum distance between drones in collective RTH plans, in meters. If not specified, a default value of 3 meters will be used.

|`velocity_xy` |no |float |Maximum horizontal velocity of drones during collective RTH, in m/s. If not specified, a default value of 4 m/s will be used.

|`velocity_z` |no |float |Maximum vertical velocity of drones during collective RTH, in m/s. If not specified, a default value of 2 m/s will be used.

|`acceleration` |no |float |Maximum acceleration of drones during collective RTH, in m/s². If not specified, a default value of 4 m/s² will be used.

|`time_resolution` |no |integer |Time interval between timestamps of the generated collective RTH plans, in seconds. If not specified, a default value of 1 second will be used.

|`first_time` |no |integer |Timestamp of the first collective RTH plan relative to show start, in seconds. If not specified, the start of the show will be used.

|`last_time` |no |integer |Timestamp of the last collective RTH plan relative to show start, in seconds. If not specified, show segment end time will be used. If there is no show segment, the end of the show will be used.
|===

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`show` |yes |string |Base64-encoded `.skyc` show file with the collective RTH plans appended

|`showDuration` |yes |float |Total duration of the show including collective RTH and landing, in seconds

|`stats` |yes |array of xref:types.adoc#collective-rth-plan-stat-entry[`CollectiveRthPlanStatEntry`] |Statistics about each generated collective RTH plan
|===

*Example request*

[source,json]
----
include::example$request_SHOW-CRTH-PLAN.json[]
----

*Example response*

[source,json]
----
include::example$response_SHOW-CRTH-PLAN.json[]
----


== `SHOW-CRTH-START` - Start collective return-to-home for a drone show

A client sends this request to the server to start a collective RTH
(return-to-home) operation for a drone show. The response contains the
time axis schedule of the show after the collective RTH request was
issued.

*Request fields*

This request has no fields.

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`schedule` |yes |array of xref:types.adoc#time-axis-schedule-segment[`TimeAxisScheduleSegment`] |Time axis schedule of the show after the collective RTH operation was initiated
|===

*Example request*

[source,json]
----
include::example$request_SHOW-CRTH-START.json[]
----

*Example response*

[source,json]
----
include::example$response_SHOW-CRTH-START.json[]
----


== `SHOW-LIGHTS` - Retrieve the current configuration of the behaviour of the LED lights on the show drones

A client sends this request to the server to obtain information about
the configuration of the behaviour of the LED lights on drones participating in the show.

The server response contains an object of type xref:types.adoc#_dronelightsconfiguration[`DroneLightsConfiguration`],
which can contain information about the type and the color of the light effect used. The type of the light effect
can either be `off` or `solid`. The former means that the GCS is not controlling the LED lights on the drones, while
the latter means that the GCS is asking the show drones to use a solid LED light.

*Request fields*

This request has no fields.

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`configuration` | yes |Object of type xref:types.adoc#_dronelightsconfiguration[`DroneLightsConfiguration`]|
Full configuration of the behaviour of the LED lights on a drone during a drone show
|===

*Example request*

[source,json]
----
include::example$request_SHOW-LIGHTS.json[]
----

*Example response*

[source,json]
----
include::example$response_SHOW-LIGHTS.json[]
----


== `SHOW-RESUME` - Resume a previously suspended drone show

A client sends this request to the server to resume a previously suspended
drone show. The response contains the time axis schedule of the show after
the resume was issued, typically starting with a preparation segment followed
by a speedup segment to ramp the show back to normal execution.

*Request fields*

This request has no fields.

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`schedule` |yes |array of xref:types.adoc#time-axis-schedule-segment[`TimeAxisScheduleSegment`] |Time axis schedule of the show after the resume was initiated
|===

*Example request*

[source,json]
----
include::example$request_SHOW-RESUME.json[]
----

*Example response*

[source,json]
----
include::example$response_SHOW-RESUME.json[]
----


== `SHOW-SETCFG` - Set the current configuration of the drone show

A client sends this request to the server to set the configuration of
the drone show.

The server responds either with an `ACK-ACK` or `ACK-NACK` message.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`configuration` | yes |Object of type xref:types.adoc#_droneshowconfiguration[`DroneShowConfiguration`]| Full configuration of a drone show
|===

*Response fields*

This request has no fields.

*Example request*

[source,json]
----
include::example$request_SHOW-SETCFG.json[]
----

*Example response*

[source,json]
----
include::example$response_ACK-ACK.json[]
----

== `SHOW-SETLIGHTS` - Set the behaviour of the LED lights on the show drones

A client sends this request to the server to set the LED lights behaviour on
the drones participating in the show.

The server responds either with an `ACK-ACK` or `ACK-NACK` message.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`configuration` | yes |Object of type xref:types.adoc#_dronelightsconfiguration[`DroneLightsConfiguration`]|
Full configuration of the behaviour of the LED lights on a drone during a drone show
|===

*Response fields*

This request has no fields.

*Example request*

[source,json]
----
include::example$request_SHOW-SETLIGHTS.json[]
----

*Example response*

[source,json]
----
include::example$response_ACK-ACK.json[]
----


== `SHOW-SUSPEND` - Suspend a drone show

A client sends this request to the server to suspend a running drone show.
The response contains the time axis schedule of the show after the
suspension was issued.

*Request fields*

This request has no fields.

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`schedule` |yes |array of xref:types.adoc#time-axis-schedule-segment[`TimeAxisScheduleSegment`] |Time axis schedule of the show after the suspension was initiated
|===

*Example request*

[source,json]
----
include::example$request_SHOW-SUSPEND.json[]
----

*Example response*

[source,json]
----
include::example$response_SHOW-SUSPEND.json[]
----
