= `SYS` — System information

== `SYS-CLOSE` - Notifies the client that the connection is about to be closed

A server sends a notification of this type to a client when the client will be
forcibly disconnected from the server. Clients may then display the reason
attached to the message to the user if it is practical to do so.

Typical reasons for a forced disconnection may be:

* the server is shutting down
* the server is limiting the number of concurrent connections
* the server is enforcing limits on the maximum duration of a connection

Note that servers are not _required_ to send this message upon a disconnection;
the message is sent only as a courtesy to the user at the other end of the
connection.

*Notification fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`reason` |no |string |An optional explanation of why the forced disconnection happened
|===

*Example notification*

[source,json]
----
{
    "type": "SYS-CLOSE",
    "reason": "Maximum number of concurrent connections exceeded"
}
----

== `SYS-MSG` - Send an arbitrary human-readable message to the client

*Notification fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`severity` |no |xref:types.adoc#_severity[`Severity`] |The severity level of the message; defaults to `"info"`
|`message` |yes |string |The message to send to the client
|===

*Example notification*

[source,json]
----
{
    "type": "SYS-MSG",
    "severity": "info",
    "message": "Free cookies in the lobby!"
}
----

== `SYS-PING` — Check whether a connection is alive

Either party in the connection may send a `SYS-PING` message to the
other party to test whether the connection is still alive. Parties
receiving a `SYS-PING` message are expected to respond with an
xref:messages/ack.adoc#_ack_ack_positive_acknowledgment[`ACK-ACK`] message as soon
as it is practical to do so.

Note that each party may decide whether it wants to send `SYS-PING`
messages over the wire periodically. Typically, the message is used to
implement "heartbeating" to detect broken connections. If the
transport protocol used to convey Flockwave messages implements
heartbeating on its own, there is no additional benefit to firing
`SYS-PING` messages. However, when Flockwave messages are transmitted
over a plain TCP connection, `SYS-PING` messages may be used by either
side to detect when the connection was dropped.

*Request fields*

This request has no fields.

*Response fields*

Responses should not be sent with this type; use
xref:messages/ack.adoc#_ack_ack_positive_acknowledgment[`ACK-ACK`] instead.

*Example request*

[source,json]
----
{
    "type": "SYS-PING"
}
----

== `SYS-TIME` - Return the current UNIX timestamp on the server

A client sends a request of this type to the server to obtain an accurate
representation of the current UNIX timestamp on the server.

This message can also be used as a simple way to detect clock skew between the
client and the server, so care should be taken on the server side to ensure the
accuracy of the returned timestamp to the extent permitted by the transport
protocol. For a more accurate time synchronization protocol, use the
xref:#sys-timesync[`SYS-TIMESYNC`] message.

*Request fields*

This request has no fields.

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`timestamp` |yes |xref:types.adoc#_timestamp[timestamp] |The current UNIX timestamp on the server at the time when the message was received.
|===

*Example request*

[source,json]
----
{
    "type": "SYS-TIME"
}
----

*Example response*

[source,json]
----
{
    "type": "SYS-TIME",
    "timestamp": 1588763723147
}
----

[#sys-timesync]
== `SYS-TIMESYNC` - Time synchronization message between a client and the server

A client sends a request of this type to the server to find out the current
UNIX timestamp of the server and an estimate of the latency of the link to the
server.

The course of the time synchronization is as follows. First, the client sends
a `SYS-TIMESYNC` message to the server with an empty timestamp list. For every
timesync message that the server receives, it simply appends the current value
of the server clock to the list and sends it back. The client then appends its
_own_ timestamp at the time when it receives the reply and sends _another_
timesync message to the server. The client and the server keeps on doing this
for a given number of iterations; the server always responds unconditionally,
while the client may decide not to send a new `SYS-TIMESYNC` message at any
point. The client and the server can then estimate the latency and the
difference between their clocks by looking at the arrival times of the
`SYS-TIMESYNC` messages.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`timestamps` |yes |array of xref:types.adoc#_timestamp[timestamp] objects |The list of timestamps collected in the current time synchronization sequence of messages; starts with an empty list when initializing a new time synchronization sequence.
|===

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`timestamps` |yes |array of xref:types.adoc#_timestamp[timestamp] objects |A copy of the timestamp list in the request, extended by the current UNIX timestamp of the server.
|===

*Example request*

[source,json]
----
{
    "type": "SYS-TIMESYNC",
    "timestamps": [1604564393147, 1604564393241]
}
----

*Example response*

[source,json]
----
{
    "type": "SYS-TIMESYNC",
    "timestamps": [1604564393147, 1604564393241, 1604564393317]
}
----

== `SYS-VER` — Version number of the server

A `SYS-VER` request retrieves the version number of the server.

*Request fields*

This request has no fields.

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`name` |no |string |The name of the server. May be used to distinguish
between multiple servers running concurrently so the operators know that
they are connecting to the right server from the client.

|`revision` |no |string |The revision number of the server, if known.
This field is optional and can be used to convey more detailed version
information than what the `version` field allows; for instance, one
could provide the Git hash of the last commit in the server’s
repository.

|`software` |yes |string |The name of the server implementation.

|`version` |yes |string |The version number of the server, in
major.minor.patch format. The patch level is optional and may be
omitted.
|===

*Example request*

[source,json]
----
{
    "type": "SYS-VER"
}
----

*Example response*

[source,json]
----
{
    "type": "SYS-VER",
    "name": "CollMot test server",
    "software": "flockwave-server",
    "version": "1.0",
    "revision": "1.0+git:e2a0dc5"
}
----
