= `SYS` — System information

== `SYS-CLOSE` - Notifies the client that the connection is about to be closed

A server sends a notification of this type to a client when the client will be
forcibly disconnected from the server. Clients may then display the reason
attached to the message to the user if it is practical to do so.

Typical reasons for a forced disconnection may be:

* the server is shutting down
* the server is limiting the number of concurrent connections
* the server is enforcing limits on the maximum duration of a connection

Note that servers are not _required_ to send this message upon a disconnection;
the message is sent only as a courtesy to the user at the other end of the
connection.

*Notification fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`reason` |no |string |An optional explanation of why the forced disconnection happened
|===

*Example notification*

[source,json]
----
{
    "type": "SYS-CLOSE",
    "reason": "Maximum number of concurrent connections exceeded"
}
----

== `SYS-MSG` - Send an arbitrary human-readable message to the client

*Notification fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`severity` |no |xref:types.adoc#_severity[`Severity`] |The severity level of the message; defaults to `"info"`
|`message` |yes |string |The message to send to the client
|===

*Example notification*

[source,json]
----
{
    "type": "SYS-MSG",
    "severity": "info",
    "message": "Free cookies in the lobby!"
}
----

== `SYS-PING` — Check whether a connection is alive

Either party in the connection may send a `SYS-PING` message to the
other party to test whether the connection is still alive. Parties
receiving a `SYS-PING` message are expected to respond with an
xref:messages/ack.adoc#_ack_ack_positive_acknowledgment[`ACK-ACK`] message as soon
as it is practical to do so.

Note that each party may decide whether it wants to send `SYS-PING`
messages over the wire periodically. Typically, the message is used to
implement "heartbeating" to detect broken connections. If the
transport protocol used to convey Flockwave messages implements
heartbeating on its own, there is no additional benefit to firing
`SYS-PING` messages. However, when Flockwave messages are transmitted
over a plain TCP connection, `SYS-PING` messages may be used by either
side to detect when the connection was dropped.

*Request fields*

This request has no fields.

*Response fields*

Responses should not be sent with this type; use
xref:messages/ack.adoc#_ack_ack_positive_acknowledgment[`ACK-ACK`] instead.

*Example request*

[source,json]
----
{
    "type": "SYS-PING"
}
----

== `SYS-VER` — Version number of the server

A `SYS-VER` request retrieves the version number of the server.

*Request fields*

This request has no fields.

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`name` |no |string |The name of the server. May be used to distinguish
between multiple servers running concurrently so the operators know that
they are connecting to the right server from the client.

|`revision` |no |string |The revision number of the server, if known.
This field is optional and can be used to convey more detailed version
information than what the `version` field allows; for instance, one
could provide the Git hash of the last commit in the server’s
repository.

|`software` |yes |string |The name of the server implementation.

|`version` |yes |string |The version number of the server, in
major.minor.patch format. The patch level is optional and may be
omitted.
|===

*Example request*

[source,json]
----
{
    "type": "SYS-VER"
}
----

*Example response*

[source,json]
----
{
    "type": "SYS-VER",
    "name": "CollMot test server",
    "software": "flockwave-server",
    "version": "1.0",
    "revision": "1.0+git:e2a0dc5"
}
----
