= `UAV` — UAV-related messages

UAVs are subtypes of objects and thus exist in the same namespace as all other
objects in the server. The messages listed in this section are specific to UAVs
and do not apply to other object types.

== `UAV-FLY` — Fly to a specific GPS coordinate

A client sends this request to the server to ask a UAV to fly to a
specific GPS coordinate and altitude. Note that it is possible to target
multiple UAVs with the same command, in which case they will be asked to
fly to the same coordinate. It is the responsibility of the software
running on the UAVs to avoid collisions in such cases, so make sure that
the UAVs can handle this.

The server responds with two lists: the first list contains the IDs of
the UAVs where the command was _accepted_ (which does not mean that the
UAVs have reached the destination, only that the UAVs have started
processing the command and act accordingly), and the second list
contains the IDs where such an attempt was not started. (Possible
reasons for failure could be: invalid UAV ID, UAV does not support
flying to a specific waypoint, waypoint is outside the designated flying
zone and so on). The server MAY decide to include more detailed
information about failed attempts in the response.

The target is specified as a
xref:types.adoc#_gpscoordinate[GPSCoordinate] object. This object MUST
contain a latitude and a longitude, but MAY omit both altitudes; in this
case, the UAV SHOULD attempt flying to the target at the same altitude
where it currently is.

Clients interested in whether the UAVs have reached their positions
should keep an eye on <<_uav_inf_basic_status_information_of_one_or_more_uavs,`UAV-INF`>>
messages.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of UAV IDs to target with this
message

|`target` |yes |xref:types.adoc#_gpscoordinate[GPSCoordinate] |The GPS
coordinate to fly to
|===

*Response fields*

The response is a xref:async.adoc#multi-async-response[multi-object async response];
each UAV is mapped to a boolean denoting whether the operation was sent
successfully to the UAV. If the UAV supports acknowledgments for this
operation, the result will indicate whether the UAV has _acknowledged_ the
operation. If the UAV does not support acknowledgments for this type of
operation, the result will indicate whether the request has been _sent_ to
the UAV.

*Example request*

[source,json]
----
{
    "type": "UAV-FLY",
    "ids": ["1", "17", "31", "spam"],
    "target": {
      "lat": 51.9976597,
      "lon": -0.7406863,
      "amsl": 93.765
    }
}
----

*Example response*

[source,json]
----
{
    "type": "UAV-FLY",
    "result": {
        "1": true,
    },
    "error": {
        "31": "UAV does not support flying to waypoints.",
        "spam": "No such UAV."
    },
    "receipts": {
        "17": "0badcafedeadbeef"
    }
}
----

== `UAV-HALT` — Initiate immediate shutdown

A client sends this request to the server to initiate an immediate
shutdown of an UAV in case of an emergency. Note that the UAV will _not_
attempt to land - typically it will stop the rotors even in mid-air. Use
this message only in emergencies.

The server responds with two lists: the first list contains the IDs of
the UAVs where a shutdown attempt was _started_ (in the sense that the
UAV has been notified that they should shut down now), and the second list
contains the IDs where such an attempt was not started. (Possible
reasons for failure could be: invalid UAV ID, UAV does not support
forced shutdown and so on). The server MAY decide to include more
detailed information about failed attempts in the response.

Clients interested in whether the shutdown attempts have succeeded
should keep an eye on <<_uav_inf_basic_status_information_of_one_or_more_uavs,`UAV-INF`>>
messages.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of UAV IDs to target with this
message
|===

*Response fields*

The response is a xref:async.adoc#multi-async-response[multi-object async response];
each UAV is mapped to a boolean denoting whether the operation was sent
successfully to the UAV. If the UAV supports acknowledgments for this
operation, the result will indicate whether the UAV has _acknowledged_ the
operation. If the UAV does not support acknowledgments for this type of
operation, the result will indicate whether the request has been _sent_ to
the UAV.

*Example request*

[source,json]
----
{
    "type": "UAV-HALT",
    "ids": ["1", "17", "31", "spam"]
}
----

*Example response*

[source,json]
----
{
    "type": "UAV-HALT",
    "result": {
        "1": true,
    },
    "error": {
        "31": "UAV does not support forced shutdown.",
        "spam": "No such UAV."
    },
    "receipts": {
        "17": "0badcafedeadbeef"
    }
}
----

== `UAV-INF` — Basic status information of one or more UAVs

A client sends this request to the server to obtain basic status
information about one or more UAVs currently known to the server.

This message may also be broadcast as a notification by the server on
its own volition to all connected Flockwave clients to notify them about
a status change of one of the UAVs.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of UAV IDs that the client is
interested in
|===

*Response and notification fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`status` |no |object of xref:types.adoc#_uavstatusinfo[`UAVStatusInfo`] |Object mapping UAV IDs to the corresponding
status information.

|`failure` |no |list of strings |List containing the UAV IDs for which
the status information could not have been retrieved.

|`reasons` |no |object |Object mapping UAV IDs to reasons why the
corresponding status information could not have been retrieved.
|===

All the UAV IDs that were specified in the request MUST appear _either_
in the `status` list or in the `failure` list. When this message is sent
as a notification, only the `status` field SHOULD be present.

*Example request*

[source,json]
----
{
    "type": "UAV-INF",
    "ids": ["1", "spam"]
}
----

*Example response*

[source,json]
----
{
    "type": "UAV-INF",
    "status": {
        "1": {
            "id": "1",
            "mode": "pos",
            "position": {
                "lat": 51.9976597,
                "lon": -0.7406863,
                "amsl": 93.765
            },
            "heading": 90,
            "attitude": {
                "roll": 0,
                "pitch": 0,
                "yaw": 90
            },
            "velocity": {
                "north": 2.0,
                "east": 2.0,
                "down": -1.0
            },
            "timestamp": "2015-12-08T08:17:41.000Z",
            "debug": "MEJBRENBRkU=",
            "error": [42]
        }
    },
    "error": {
        "spam": "No such UAV."
    }
}
----

[#uav-land]
== `UAV-LAND` — Initiate unsupervised landing

A client send this request to the server to initiate unsupervised
landing on one or more UAVs. The server responds with two lists: the
first list contains the IDs of the UAVs where an unsupervised landing
attempt was _started_ (in the sense that the UAV has been notified that
they should land now), and the second list contains the IDs where such
an attempt was not started. (Possible reasons for failure could be:
invalid UAV ID, UAV does not support unsupervised landing and so on).
The server MAY decide to include more detailed information about failed
attempts in the response.

Clients interested in whether the landing attempts have succeeded should
keep an eye on <<_uav_inf_basic_status_information_of_one_or_more_uavs,`UAV-INF`>>
messages.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of UAV IDs to target with this
message
|===

*Response fields*

The response is a xref:async.adoc#multi-async-response[multi-object async response];
each UAV is mapped to a boolean denoting whether the operation was sent
successfully to the UAV. If the UAV supports acknowledgments for this
operation, the result will indicate whether the UAV has _acknowledged_ the
operation. If the UAV does not support acknowledgments for this type of
operation, the result will indicate whether the request has been _sent_ to
the UAV.

*Example request*

[source,json]
----
{
    "type": "UAV-LAND",
    "ids": ["1", "17", "31", "spam"]
}
----

*Example response*

[source,json]
----
{
    "type": "UAV-LAND",
    "result": {
        "1": true,
    },
    "error": {
        "31": "UAV is a beacon.",
        "spam": "No such UAV."
    },
    "receipts": {
        "17": "0badcafedeadbeef"
    }
}
----

== `UAV-LIST` — List of all the UAVs known by the server

A client sends this request to the server to request the list of all
UAVs currently known by the server. The semantics of ``knowing'' a UAV
is left up to the server implementation and configuration; typically,
the server will return an UAV ID in the response if it has received a
status message from the given UAV recently, typically in the last few
minutes.

This message is equivalent to sending an `OBJ-LIST` message with its
`filter` set to `uav`; it exists solely for compatibility with legacy
clients and will be deprecated in Flockwave 2.0.

*Request fields*

This request has no fields.

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of UAV IDs that the server knows
|===

*Example request*

[source,json]
----
{
    "type": "UAV-LIST"
}
----

*Example response*

[source,json]
----
{
    "type": "UAV-LIST",
    "ids": ["1", "17", "31"]
}
----

== `UAV-RST` — Send reboot request

A client sends this request to the server to initiate the reboot of the
entire UAV or some subsystem of it. Note that this is a potentially dangerous
operation; this message only if the UAV is on the ground or if you are sure
that the rebooted subsystem does not affect the normal operation of the UAV
during flight.

The server responds with two lists: the first list contains the IDs of
the UAVs where a reboot attempt was _started_ (in the sense that the
UAV has been notified that they should reboot), and the second list
contains the IDs where such an attempt was not started. (Possible
reasons for failure could be: invalid UAV ID, UAV does not support
rebooting and so on). The server MAY decide to include more detailed
information about failed attempts in the response.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of UAV IDs to target with this
message
|`component` |no |string |The name of the UAV component to reboot. The list
of allowed names depends on the type of the UAV. When omitted or empty, the
entire UAV will be rebooted as if it was turned off and then on again.
|===

*Response fields*

The response is a xref:async.adoc#multi-async-response[multi-object async response];
each UAV is mapped to a boolean denoting whether the operation was sent
successfully to the UAV. If the UAV supports acknowledgments for this
operation, the result will indicate whether the UAV has _acknowledged_ the
operation. If the UAV does not support acknowledgments for this type of
operation, the result will indicate whether the request has been _sent_ to
the UAV.

All the UAV IDs that were specified in the request MUST appear _either_
in the `success` list or in the `failure` list.

*Example request*

[source,json]
----
{
    "type": "UAV-RST",
    "ids": ["1", "17", "31", "spam"],
    "component": "autopilot"
}
----

*Example response*

[source,json]
----
{
    "type": "UAV-RST",
    "result": {
        "1": true,
    },
    "error": {
        "31": "UAV does not support rebooting.",
        "spam": "No such UAV."
    },
    "receipts": {
        "17": "0badcafedeadbeef"
    }
}
----

== `UAV-RTH` — Initiate return to home position

A client send this request to the server to request some of the UAVs to
return to their home positions.

The server responds with two lists: the first list contains the IDs of
the UAVs where an unsupervised landing attempt was _started_ (in the
sense that the UAV has been notified that they should return to their
home positions now), and the second list contains the IDs where such an
attempt was not started. (Possible reasons for failure could be: invalid
UAV ID, UAV does not know the concept of a home position and so on). The
server MAY decide to include more detailed information about failed
attempts in the response.

Clients interested in whether the targeted UAVs have returned to their
home positions should keep an eye on
<<_uav_inf_basic_status_information_of_one_or_more_uavs,`UAV-INF`>>
messages and watch the GPS coordinates of the UAVs.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of UAV IDs to target with this
message
|===

*Response fields*

The response is a xref:async.adoc#multi-async-response[multi-object async response];
each UAV is mapped to a boolean denoting whether the operation was sent
successfully to the UAV. If the UAV supports acknowledgments for this
operation, the result will indicate whether the UAV has _acknowledged_ the
operation. If the UAV does not support acknowledgments for this type of
operation, the result will indicate whether the request has been _sent_ to
the UAV.

*Example request*

[source,json]
----
{
    "type": "UAV-RTH",
    "ids": ["1", "17", "31", "spam"]
}
----

*Example response*

[source,json]
----
{
    "type": "UAV-RTH",
    "result": {
        "1": true,
    },
    "error": {
        "31": "UAV is a beacon.",
        "spam": "No such UAV."
    },
    "receipts": {
        "17": "0badcafedeadbeef"
    }
}
----

== `UAV-SIGNAL` - Emit light or audio signals

A client sends this request to the server to ask one or more UAVs to emit
a light or audio signal in order to attract attention. This is useful if you
are trying to find a lost drone in the field or if you want to identify a
drone needing battery replacement in a drone swarm, given its ID.

The message specifies what sort of signal should be emitted; right now the
protocol supports `light` and `sound` signals, but more signal types may be
added in the future. As the signal types are merely strings, the protocol can
easily be extended in the future with additional signal types, and UAVs that
do not know or do not support a specific signal type should simply ignore the
unknown ones.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of UAV IDs to target with this
message

|`signals` |yes |list of strings |The list of signal types that the targeted UAVs
should emit

|`duration` |yes |integer |The duration of the signal, in milliseconds. UAVs
that do not support prescribed signal durations may ignore it and fall back to
a default duration.
|===

*Response fields*

The response is a xref:async.adoc#multi-async-response[multi-object async response];
each UAV is mapped to a boolean denoting whether the operation was sent
successfully to the UAV. If the UAV supports acknowledgments for this
operation, the result will indicate whether the UAV has _acknowledged_ the
operation. If the UAV does not support acknowledgments for this type of
operation, the result will indicate whether the request has been _sent_ to
the UAV.

*Example request*

[source,json]
----
{
    "type": "UAV-SIGNAL",
    "ids": ["1", "17", "31", "spam"],
    "signals": ["sound", "light"],
    "duration": 5000
}
----

*Example response*

[source,json]
----
{
    "type": "UAV-SIGNAL",
    "result": {
        "1": true,
    },
    "error": {
        "31": "UAV is a beacon.",
        "spam": "No such UAV."
    },
    "receipts": {
        "17": "0badcafedeadbeef"
    }
}
----

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`success` |no |list of strings |The list of UAV IDs to which the
request was sent

|`failure` |no |list of strings |The list of UAV IDs to which the
request was _not_ sent

|`reasons` |no |object |Object mapping UAV IDs to explanations about why
the request failed for these UAVs.
|===

== `UAV-TAKEOFF` — Initiate unsupervised take-off

A client sends this request to the server to initiate unsupervised
take-off on one or more UAVs. The server responds with two lists: the
first list contains the IDs of the UAVs where an unsupervised take-off
was _started_ (in the sense that the UAV has been notified that they
should take off now), and the second list contains the IDs where such an
attempt was not started. (Possible reasons for failure could be: invalid
UAV ID, UAV does not support unsupervised take-off and so on). The
server MAY decide to include more detailed information about failed
attempts in the response.

Clients interested in whether the take-off attempts have succeeded
should keep an eye on <<_uav_inf_basic_status_information_of_one_or_more_uavs,`UAV-INF`>>
messages and watch the status flags of the UAVs.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of UAV IDs to target with this
message
|===

*Response fields*

The response is a xref:async.adoc#multi-async-response[multi-object async response];
each UAV is mapped to a boolean denoting whether the operation was sent
successfully to the UAV. If the UAV supports acknowledgments for this
operation, the result will indicate whether the UAV has _acknowledged_ the
operation. If the UAV does not support acknowledgments for this type of
operation, the result will indicate whether the request has been _sent_ to
the UAV.

*Example request*

[source,json]
----
{
    "type": "UAV-TAKEOFF",
    "ids": ["1", "17", "31", "spam"]
}
----

*Example response*

[source,json]
----
{
    "type": "UAV-TAKEOFF",
    "result": {
        "1": true,
    },
    "error": {
        "31": "UAV is a beacon.",
        "spam": "No such UAV."
    },
    "receipts": {
        "17": "0badcafedeadbeef"
    }
}
----
