== `UAV` — UAV-related messages

=== `UAV-FLY` — Fly to a specific GPS coordinate

A client sends this request to the server to ask a UAV to fly to a
specific GPS coordinate and altitude. Note that it is possible to target
multiple UAVs with the same command, in which case they will be asked to
fly to the same coordinate. It is the responsibility of the software
running on the UAVs to avoid collisions in such cases, so make sure that
the UAVs can handle this.

The server responds with two lists: the first list contains the IDs of
the UAVs where the command was _accepted_ (which does not mean that the
UAVs have reached the destination, only that the UAVs have started
processing the command and act accordingly), and the second list
contains the IDs where such an attempt was not started. (Possible
reasons for failure could be: invalid UAV ID, UAV does not support
flying to a specific waypoint, waypoint is outside the designated flying
zone and so on). The server MAY decide to include more detailed
information about failed attempts in the response.

The target is specified as a
xref:types.adoc#_gpscoordinate[GPSCoordinate] object. This object MUST
contain a latitude and a longitude, but MAY omit both altitudes; in this
case, the UAV SHOULD attempt flying to the target at the same altitude
where it currently is.

Clients interested in whether the UAVs have reached their positions
should keep an eye on <<_uav_inf_basic_status_information_of_one_or_more_uavs,`UAV-INF`>>
messages.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of UAV IDs to target with this
message

|`target` |yes |xref:types.adoc#_gpscoordinate[GPSCoordinate] |The GPS
coordinate to fly to
|===

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`success` |no |list of strings |The list of UAV IDs to which the
request was sent

|`failure` |no |list of strings |The list of UAV IDs to which the
request was _not_ sent

|`reasons` |no |object |Object mapping UAV IDs to explanations about why
the request failed for these UAVs.
|===

All the UAV IDs that were specified in the request MUST appear _either_
in the `success` list or in the `failure` list.

*Example request*

[source,json]
----
{
    "type": "UAV-FLY",
    "ids": ["1", "17", "31", "spam"],
    "target": {
      "lat": 51.9976597,
      "lon": -0.7406863,
      "amsl": 93.765
    }
}
----

*Example response*

[source,json]
----
{
    "type": "UAV-FLY",
    "success": ["1", "17"],
    "failure": ["31", "spam"],
    "reasons": {
        "31": "UAV does not support flying to waypoints.",
        "spam": "No such UAV."
    }
}
----

=== `UAV-HALT` — Initiate immediate shutdown

A client sends this request to the server to initiate an immediate
shutdown of an UAV in case of an emergency. Note that the UAV will _not_
attempt to land - typically it will stop the rotors even in mid-air. Use
this message only in emergencies.

The server responds with two lists: the first list contains the IDs of
the UAVs where a shutdown attempt was _started_ (in the sense that the
UAV has been notified that they should land now), and the second list
contains the IDs where such an attempt was not started. (Possible
reasons for failure could be: invalid UAV ID, UAV does not support
forced shutdown and so on). The server MAY decide to include more
detailed information about failed attempts in the response.

Clients interested in whether the shutdown attempts have succeeded
should keep an eye on <<_uav_inf_basic_status_information_of_one_or_more_uavs,`UAV-INF`>>
messages.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of UAV IDs to target with this
message
|===

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`success` |no |list of strings |The list of UAV IDs to which the
request was sent

|`failure` |no |list of strings |The list of UAV IDs to which the
request was _not_ sent

|`reasons` |no |object |Object mapping UAV IDs to explanations about why
the request failed for these UAVs.
|===

All the UAV IDs that were specified in the request MUST appear _either_
in the `success` list or in the `failure` list.

*Example request*

[source,json]
----
{
    "type": "UAV-HALT",
    "ids": ["1", "17", "31", "spam"]
}
----

*Example response*

[source,json]
----
{
    "type": "UAV-HALT",
    "success": ["1", "17"],
    "failure": ["31", "spam"],
    "reasons": {
        "31": "UAV does not support forced shutdown.",
        "spam": "No such UAV."
    }
}
----

=== `UAV-INF` — Basic status information of one or more UAVs

A client sends this request to the server to obtain basic status
information about one or more UAVs currently known to the server.

This message may also be broadcast as a notification by the server on
its own volition to all connected Flockwave clients to notify them about
a status change of one of the UAVs.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of UAV IDs that the client is
interested in
|===

*Response and notification fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`status` |no |object of xref:types.adoc#_uavstatusinfo[`UAVStatusInfo`] |Object mapping UAV IDs to the corresponding
status information.

|`failure` |no |list of strings |List containing the UAV IDs for which
the status information could not have been retrieved.

|`reasons` |no |object |Object mapping UAV IDs to reasons why the
corresponding status information could not have been retrieved.
|===

All the UAV IDs that were specified in the request MUST appear _either_
in the `status` list or in the `failure` list. When this message is sent
as a notification, only the `status` field SHOULD be present.

*Example request*

[source,json]
----
{
    "type": "UAV-INF",
    "ids": ["1", "spam"]
}
----

*Example response*

[source,json]
----
{
    "type": "UAV-INF",
    "status": {
        "1": {
            "id": "1",
            "algorithm": "flocking",
            "position": {
                "lat": 51.9976597,
                "lon": -0.7406863,
                "amsl": 93.765
            },
            "heading": 90,
            "attitude": {
                "roll": 0,
                "pitch": 0,
                "yaw": 90
            },
            "velocity": {
                "north": 2.0,
                "east": 2.0,
                "down": -1.0
            },
            "timestamp": "2015-12-08T08:17:41.000Z",
            "debug": "MEJBRENBRkU=",
            "error": [42]
        }
    },
    "failure": ["spam"],
    "reasons": {
        "spam": "No such UAV."
    }
}
----

=== `UAV-LAND` — Initiate unsupervised landing

A client send this request to the server to initiate unsupervised
landing on one or more UAVs. The server responds with two lists: the
first list contains the IDs of the UAVs where an unsupervised landing
attempt was _started_ (in the sense that the UAV has been notified that
they should land now), and the second list contains the IDs where such
an attempt was not started. (Possible reasons for failure could be:
invalid UAV ID, UAV does not support unsupervised landing and so on).
The server MAY decide to include more detailed information about failed
attempts in the response.

Clients interested in whether the landing attempts have succeeded should
keep an eye on <<_uav_inf_basic_status_information_of_one_or_more_uavs,`UAV-INF`>>
messages.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of UAV IDs to target with this
message
|===

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`success` |no |list of strings |The list of UAV IDs to which the
request was sent

|`failure` |no |list of strings |The list of UAV IDs to which the
request was _not_ sent

|`reasons` |no |object |Object mapping UAV IDs to explanations about why
the request failed for these UAVs.
|===

*Example request*

[source,json]
----
{
    "type": "UAV-LAND",
    "ids": ["1", "17", "31", "spam"]
}
----

*Example response*

[source,json]
----
{
    "type": "UAV-LAND",
    "success": ["1", "17"],
    "failure": ["31", "spam"],
    "reasons": {
        "31": "UAV is a beacon.",
        "spam": "No such UAV."
    }
}
----

=== `UAV-LIST` — List of all the UAVs known by the server

A client sends this request to the server to request the list of all
UAVs currently known by the server. The semantics of ``knowing'' a UAV
is left up to the server implementation and configuration; typically,
the server will return an UAV ID in the response if it has received a
status message from the given UAV recently, typically in the last few
minutes.

*Request fields*

This request has no fields.

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of UAV IDs that the server knows
|===

*Example request*

[source,json]
----
{
    "type": "UAV-LIST"
}
----

*Example response*

[source,json]
----
{
    "type": "UAV-LIST",
    "ids": ["1", "17", "31"]
}
----

=== `UAV-RTH` — Initiate return to home position

A client send this request to the server to request some of the UAVs to
return to their home positions.

The server responds with two lists: the first list contains the IDs of
the UAVs where an unsupervised landing attempt was _started_ (in the
sense that the UAV has been notified that they should return to their
home positions now), and the second list contains the IDs where such an
attempt was not started. (Possible reasons for failure could be: invalid
UAV ID, UAV does not know the concept of a home position and so on). The
server MAY decide to include more detailed information about failed
attempts in the response.

Clients interested in whether the targeted UAVs have returned to their
home positions should keep an eye on
<<_uav_inf_basic_status_information_of_one_or_more_uavs,`UAV-INF`>>
messages and watch the GPS coordinates of the UAVs.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of UAV IDs to target with this
message
|===

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`success` |no |list of strings |The list of UAV IDs to which the
request was sent

|`failure` |no |list of strings |The list of UAV IDs to which the
request was _not_ sent

|`reasons` |no |object |Object mapping UAV IDs to explanations about why
the request failed for these UAVs.
|===

*Example request*

[source,json]
----
{
    "type": "UAV-RTH",
    "ids": ["1", "17", "31", "spam"]
}
----

*Example response*

[source,json]
----
{
    "type": "UAV-RTH",
    "success": ["1", "17"],
    "failure": ["31", "spam"],
    "reasons": {
        "31": "UAV is a beacon.",
        "spam": "No such UAV."
    }
}
----

=== `UAV-TAKEOFF` — Initiate unsupervised take-off

A client send this request to the server to initiate unsupervised
take-off on one or more UAVs. The server responds with two lists: the
first list contains the IDs of the UAVs where an unsupervised take-off
was _started_ (in the sense that the UAV has been notified that they
should take off now), and the second list contains the IDs where such an
attempt was not started. (Possible reasons for failure could be: invalid
UAV ID, UAV does not support unsupervised take-off and so on). The
server MAY decide to include more detailed information about failed
attempts in the response.

Clients interested in whether the take-off attempts have succeeded
should keep an eye on <<_uav_inf_basic_status_information_of_one_or_more_uavs,`UAV-INF`>>
messages and watch the status flags of the UAVs.

*Request fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`ids` |yes |list of strings |The list of UAV IDs to target with this
message
|===

*Response fields*

[width="100%",cols="15%,10%,25%,50%",options="header",]
|===
|Name |Required? |Type |Description
|`success` |no |list of strings |The list of UAV IDs to which the
request was sent

|`failure` |no |list of strings |The list of UAV IDs to which the
request was _not_ sent

|`reasons` |no |object |Object mapping UAV IDs to explanations about why
the request failed for these UAVs.
|===

*Example request*

[source,json]
----
{
    "type": "UAV-TAKEOFF",
    "ids": ["1", "17", "31", "spam"]
}
----

*Example response*

[source,json]
----
{
    "type": "UAV-TAKEOFF",
    "success": ["1", "17"],
    "failure": ["31", "spam"],
    "reasons": {
        "31": "UAV is a beacon.",
        "spam": "No such UAV."
    }
}
----
